'use client';

import { useState, useEffect, useCallback } from 'react';
import { Users, Search, Mail, MessageSquare, Hash, Filter, ChevronDown, Check, X, Edit2 } from 'lucide-react';
import Header from '@/components/shared/Header';
import Image from 'next/image';

interface Contact {
  id: string;
  name: string;
  address: string;
  channels: { channel: string; address: string; frequency: number }[];
  relationshipType: string;
  confidence: number;
  confirmed: boolean;
  mainChannel: string;
  messageCount: number;
  lastContactAt: string;
  isAutoGenerated: boolean;
}

interface ContactStats {
  total: number;
  byRelationship: Record<string, number>;
  byChannel: Record<string, number>;
  unconfirmedCount: number;
}

const RELATIONSHIP_LABELS: Record<string, { label: string; color: string }> = {
  internal: { label: '自社メンバー', color: 'bg-blue-100 text-blue-700' },
  client: { label: 'クライアント', color: 'bg-green-100 text-green-700' },
  partner: { label: 'パートナー', color: 'bg-purple-100 text-purple-700' },
  unknown: { label: '未分類', color: 'bg-slate-100 text-slate-500' },
};

const CHANNEL_ICONS: Record<string, string> = {
  email: '/icons/gmail.svg',
  slack: '/icons/slack.svg',
  chatwork: '/icons/chatwork.svg',
};

function formatDate(dateStr: string): string {
  if (!dateStr) return '-';
  const d = new Date(dateStr);
  const now = new Date();
  const diff = now.getTime() - d.getTime();
  const days = Math.floor(diff / (1000 * 60 * 60 * 24));
  if (days === 0) return '今日';
  if (days === 1) return '昨日';
  if (days < 7) return `${days}日前`;
  if (days < 30) return `${Math.floor(days / 7)}週間前`;
  return d.toLocaleDateString('ja-JP', { month: 'short', day: 'numeric' });
}

function getInitials(name: string): string {
  if (!name) return '?';
  const parts = name.split(/[\s　]+/);
  if (parts.length >= 2) return (parts[0][0] + parts[1][0]).toUpperCase();
  return name.slice(0, 2).toUpperCase();
}

const AVATAR_COLORS = [
  'bg-blue-500', 'bg-green-500', 'bg-purple-500', 'bg-orange-500',
  'bg-pink-500', 'bg-teal-500', 'bg-indigo-500', 'bg-rose-500',
];

function getAvatarColor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  }
  return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length];
}

export default function ContactsPage() {
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [stats, setStats] = useState<ContactStats | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [filterRelationship, setFilterRelationship] = useState('all');
  const [filterChannel, setFilterChannel] = useState('all');
  const [selectedContact, setSelectedContact] = useState<Contact | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editRelationship, setEditRelationship] = useState('');

  const fetchContacts = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams();
      if (search) params.set('search', search);
      if (filterRelationship !== 'all') params.set('relationship', filterRelationship);
      if (filterChannel !== 'all') params.set('channel', filterChannel);

      const res = await fetch(`/api/contacts?${params}`);
      const data = await res.json();
      if (data.success) {
        setContacts(data.data);
        setStats(data.stats);
      } else {
        setError(data.error || '取得に失敗しました');
      }
    } catch {
      setError('通信エラーが発生しました');
    } finally {
      setIsLoading(false);
    }
  }, [search, filterRelationship, filterChannel]);

  useEffect(() => {
    fetchContacts();
  }, [fetchContacts]);

  // 関係タイプ更新
  const updateRelationship = async (contact: Contact, newType: string) => {
    try {
      const res = await fetch('/api/contacts', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: contact.id,
          address: contact.address,
          name: contact.name,
          relationshipType: newType,
          confirmed: true,
          mainChannel: contact.mainChannel,
          messageCount: contact.messageCount,
          lastContactAt: contact.lastContactAt,
        }),
      });
      const data = await res.json();
      if (data.success) {
        // ローカル状態を更新
        setContacts((prev) =>
          prev.map((c) =>
            c.id === contact.id
              ? { ...c, relationshipType: newType, confirmed: true, id: data.data?.id || c.id }
              : c
          )
        );
        setEditingId(null);
      }
    } catch (err) {
      console.error('更新エラー:', err);
    }
  };

  return (
    <div className="flex flex-col h-screen bg-white">
      <Header />
      <div className="flex-1 overflow-hidden flex flex-col">
        {/* ヘッダー + 統計 */}
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <Users className="w-5 h-5 text-slate-600" />
              <h1 className="text-lg font-bold text-slate-900">コンタクト</h1>
              {stats && (
                <span className="text-sm text-slate-400">{stats.total}件</span>
              )}
            </div>
          </div>

          {/* 統計バッジ */}
          {stats && (
            <div className="flex gap-2 mb-3">
              {Object.entries(RELATIONSHIP_LABELS).map(([key, { label, color }]) => {
                const count = (stats.byRelationship as Record<string, number>)[key] || 0;
                if (count === 0 && key !== 'unknown') return null;
                return (
                  <button
                    key={key}
                    onClick={() => setFilterRelationship(filterRelationship === key ? 'all' : key)}
                    className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium transition-colors ${
                      filterRelationship === key ? 'ring-2 ring-offset-1 ring-blue-400' : ''
                    } ${color}`}
                  >
                    {label} <span className="font-bold">{count}</span>
                  </button>
                );
              })}
            </div>
          )}

          {/* 検索 + フィルター */}
          <div className="flex gap-2">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
              <input
                type="text"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="名前やアドレスで検索..."
                className="w-full pl-9 pr-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <select
              value={filterChannel}
              onChange={(e) => setFilterChannel(e.target.value)}
              className="px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">全チャネル</option>
              <option value="email">Gmail</option>
              <option value="slack">Slack</option>
              <option value="chatwork">Chatwork</option>
            </select>
          </div>
        </div>

        {/* コンタクト一覧テーブル */}
        <div className="flex-1 overflow-y-auto">
          {isLoading ? (
            <div className="flex items-center justify-center h-64 text-slate-400">
              <div className="text-center">
                <div className="animate-spin text-2xl mb-2">&#8987;</div>
                <p className="text-sm">読み込み中...</p>
              </div>
            </div>
          ) : error ? (
            <div className="p-6 text-center text-red-500">{error}</div>
          ) : contacts.length === 0 ? (
            <div className="flex items-center justify-center h-64 text-slate-400">
              <div className="text-center">
                <Users className="w-12 h-12 mx-auto mb-3 text-slate-300" />
                <p className="text-sm">コンタクトがありません</p>
                <p className="text-xs mt-1">インボックスでメッセージを受信すると自動的に追加されます</p>
              </div>
            </div>
          ) : (
            <table className="w-full">
              <thead className="bg-slate-50 sticky top-0 z-10">
                <tr className="border-b border-slate-200">
                  <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">名前</th>
                  <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">アドレス</th>
                  <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">チャネル</th>
                  <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">関係</th>
                  <th className="text-right text-xs font-semibold text-slate-500 px-4 py-3">件数</th>
                  <th className="text-right text-xs font-semibold text-slate-500 px-4 py-3">最終連絡</th>
                </tr>
              </thead>
              <tbody>
                {contacts.map((contact) => (
                  <tr
                    key={contact.id}
                    onClick={() => setSelectedContact(selectedContact?.id === contact.id ? null : contact)}
                    className={`border-b border-slate-100 hover:bg-blue-50 cursor-pointer transition-colors ${
                      selectedContact?.id === contact.id ? 'bg-blue-50' : ''
                    }`}
                  >
                    {/* 名前 + アバター */}
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-3">
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold ${getAvatarColor(contact.name)}`}>
                          {getInitials(contact.name)}
                        </div>
                        <div>
                          <div className="text-sm font-medium text-slate-900">{contact.name}</div>
                          {contact.isAutoGenerated && (
                            <span className="text-[10px] text-amber-500">自動検出</span>
                          )}
                        </div>
                      </div>
                    </td>

                    {/* アドレス */}
                    <td className="px-4 py-3">
                      <span className="text-xs text-slate-500 truncate block max-w-[200px]">{contact.address || '-'}</span>
                    </td>

                    {/* チャネル */}
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-1">
                        {CHANNEL_ICONS[contact.mainChannel] ? (
                          <Image
                            src={CHANNEL_ICONS[contact.mainChannel]}
                            alt={contact.mainChannel}
                            width={16}
                            height={16}
                          />
                        ) : (
                          <Mail className="w-4 h-4 text-slate-400" />
                        )}
                      </div>
                    </td>

                    {/* 関係タイプ */}
                    <td className="px-4 py-3" onClick={(e) => e.stopPropagation()}>
                      {editingId === contact.id ? (
                        <div className="flex items-center gap-1">
                          <select
                            value={editRelationship}
                            onChange={(e) => setEditRelationship(e.target.value)}
                            className="text-xs border border-slate-300 rounded px-1.5 py-1 focus:outline-none focus:ring-1 focus:ring-blue-500"
                          >
                            <option value="internal">自社メンバー</option>
                            <option value="client">クライアント</option>
                            <option value="partner">パートナー</option>
                            <option value="unknown">未分類</option>
                          </select>
                          <button
                            onClick={() => updateRelationship(contact, editRelationship)}
                            className="p-0.5 text-green-600 hover:text-green-800"
                          >
                            <Check className="w-3.5 h-3.5" />
                          </button>
                          <button
                            onClick={() => setEditingId(null)}
                            className="p-0.5 text-slate-400 hover:text-slate-600"
                          >
                            <X className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      ) : (
                        <button
                          onClick={() => {
                            setEditingId(contact.id);
                            setEditRelationship(contact.relationshipType);
                          }}
                          className="inline-flex items-center gap-1 group"
                        >
                          <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-medium ${
                            RELATIONSHIP_LABELS[contact.relationshipType]?.color || RELATIONSHIP_LABELS.unknown.color
                          }`}>
                            {RELATIONSHIP_LABELS[contact.relationshipType]?.label || '未分類'}
                          </span>
                          <Edit2 className="w-3 h-3 text-slate-300 opacity-0 group-hover:opacity-100 transition-opacity" />
                        </button>
                      )}
                    </td>

                    {/* メッセージ件数 */}
                    <td className="px-4 py-3 text-right">
                      <span className="text-sm text-slate-700 font-medium">{contact.messageCount}</span>
                    </td>

                    {/* 最終連絡 */}
                    <td className="px-4 py-3 text-right">
                      <span className="text-xs text-slate-400">{formatDate(contact.lastContactAt)}</span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        {/* 選択時の詳細パネル（下部） */}
        {selectedContact && (
          <div className="border-t border-slate-200 bg-slate-50 p-4">
            <div className="flex items-start gap-4">
              <div className={`w-12 h-12 rounded-full flex items-center justify-center text-white text-lg font-bold ${getAvatarColor(selectedContact.name)}`}>
                {getInitials(selectedContact.name)}
              </div>
              <div className="flex-1">
                <h3 className="text-base font-bold text-slate-900">{selectedContact.name}</h3>
                <p className="text-sm text-slate-500 mt-0.5">{selectedContact.address || 'アドレス未取得'}</p>
                <div className="flex items-center gap-4 mt-2">
                  <span className="text-xs text-slate-500">
                    メインチャネル: <strong>{selectedContact.mainChannel}</strong>
                  </span>
                  <span className="text-xs text-slate-500">
                    やり取り: <strong>{selectedContact.messageCount}件</strong>
                  </span>
                  <span className="text-xs text-slate-500">
                    最終: <strong>{formatDate(selectedContact.lastContactAt)}</strong>
                  </span>
                </div>
                {selectedContact.channels && selectedContact.channels.length > 1 && (
                  <div className="mt-2 flex gap-2">
                    {selectedContact.channels.map((ch, i) => (
                      <span key={i} className="inline-flex items-center gap-1 text-xs bg-white border border-slate-200 px-2 py-1 rounded">
                        {CHANNEL_ICONS[ch.channel] && (
                          <Image src={CHANNEL_ICONS[ch.channel]} alt={ch.channel} width={12} height={12} />
                        )}
                        {ch.address} ({ch.frequency}件)
                      </span>
                    ))}
                  </div>
                )}
              </div>
              <button
                onClick={() => setSelectedContact(null)}
                className="text-slate-400 hover:text-slate-600"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
