'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { Users, Search, Mail, Shield, ShieldOff, Check, X, Edit2, Building2, MessageSquare, Save, UserPlus, Clock, FolderOpen, Plus, GitMerge, AlertTriangle, Link2 } from 'lucide-react';
import Header from '@/components/shared/Header';
import QuickAddContactModal from '@/components/contacts/QuickAddContactModal';
import Image from 'next/image';

// ========================================
// 型定義
// ========================================
interface ActiveChannel {
  channel: string;
  name: string;
}

interface Contact {
  id: string;
  name: string;
  address: string;
  channels: { channel: string; address: string; frequency: number }[];
  allChannels: string[];
  relationshipType: string;
  confidence: number;
  confirmed: boolean;
  mainChannel: string;
  messageCount: number;
  lastContactAt: string;
  isAutoGenerated: boolean;
  // コンテキストフィールド
  companyName: string;
  department: string;
  notes: string;
  visibility: string;
  activeChannels: ActiveChannel[];
  // Phase 34: 組織・チームメンバー
  organization_id?: string;
  is_team_member?: boolean;
}

// Phase 34: 活動履歴の型
interface Activity {
  id: string;
  type: 'event' | 'message';
  title: string;
  content: string | null;
  eventType: string;
  timestamp: string;
}

// Phase 34: 組織の型
interface OrgOption {
  id: string;
  name: string;
}

// Phase 34: プロジェクトの型
interface ProjectOption {
  id: string;
  name: string;
}

// Phase 35: 重複候補グループの型
interface DuplicateContact {
  id: string;
  name: string;
  relationship_type: string;
  main_channel: string;
  message_count: number;
  last_contact_at: string;
  company_name: string | null;
}

interface DuplicateGroup {
  name: string;
  contacts: DuplicateContact[];
}

interface ContactStats {
  total: number;
  byRelationship: Record<string, number>;
  byChannel: Record<string, number>;
  unconfirmedCount: number;
}

interface BlocklistEntry {
  id: string;
  address: string;
  match_type: 'exact' | 'domain';
  reason: string | null;
  created_at: string;
}

// ========================================
// 定数
// ========================================
const RELATIONSHIP_LABELS: Record<string, { label: string; color: string }> = {
  internal: { label: '自社メンバー', color: 'bg-blue-100 text-blue-700' },
  client: { label: 'クライアント', color: 'bg-green-100 text-green-700' },
  partner: { label: 'パートナー', color: 'bg-purple-100 text-purple-700' },
  unknown: { label: '未分類', color: 'bg-slate-100 text-slate-500' },
};

const CHANNEL_ICONS: Record<string, string> = {
  email: '/icons/gmail.svg',
  slack: '/icons/slack.svg',
  chatwork: '/icons/chatwork.svg',
};

const CHANNEL_LABELS: Record<string, string> = {
  email: 'メール',
  slack: 'Slack',
  chatwork: 'Chatwork',
};

// ========================================
// ユーティリティ
// ========================================
function formatDate(dateStr: string): string {
  if (!dateStr) return '-';
  const d = new Date(dateStr);
  const now = new Date();
  const diff = now.getTime() - d.getTime();
  const days = Math.floor(diff / (1000 * 60 * 60 * 24));
  if (days === 0) return '今日';
  if (days === 1) return '昨日';
  if (days < 7) return `${days}日前`;
  if (days < 30) return `${Math.floor(days / 7)}週間前`;
  return d.toLocaleDateString('ja-JP', { month: 'short', day: 'numeric' });
}

function getInitials(name: string): string {
  if (!name) return '?';
  const parts = name.split(/[\s　]+/);
  if (parts.length >= 2) return (parts[0][0] + parts[1][0]).toUpperCase();
  return name.slice(0, 2).toUpperCase();
}

const AVATAR_COLORS = [
  'bg-blue-500', 'bg-green-500', 'bg-purple-500', 'bg-orange-500',
  'bg-pink-500', 'bg-teal-500', 'bg-indigo-500', 'bg-rose-500',
];

function getAvatarColor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  }
  return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length];
}

// ========================================
// メインコンポーネント
// ========================================
export default function ContactsPage() {
  const [activeTab, setActiveTab] = useState<'contacts' | 'blocklist'>('contacts');

  // --- コンタクト関連state ---
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [stats, setStats] = useState<ContactStats | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');
  const [filterRelationship, setFilterRelationship] = useState('all');
  const [filterChannel, setFilterChannel] = useState('all');

  // Phase 29: 検索のデバウンス（300ms）
  const debounceTimerRef = useRef<NodeJS.Timeout | null>(null);
  useEffect(() => {
    if (debounceTimerRef.current) {
      clearTimeout(debounceTimerRef.current);
    }
    debounceTimerRef.current = setTimeout(() => {
      setDebouncedSearch(search);
    }, 300);
    return () => {
      if (debounceTimerRef.current) clearTimeout(debounceTimerRef.current);
    };
  }, [search]);
  const [selectedContact, setSelectedContact] = useState<Contact | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editRelationship, setEditRelationship] = useState('');
  const [actionResult, setActionResult] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  // --- エンリッチ（自動取得）state ---
  const [isEnriching, setIsEnriching] = useState(false);
  const [enrichResult, setEnrichResult] = useState<{ enriched: number; details: { name: string; updates: string[] }[] } | null>(null);

  // --- 詳細パネル編集state ---
  const [editCompany, setEditCompany] = useState('');
  const [editDepartment, setEditDepartment] = useState('');
  const [editNotes, setEditNotes] = useState('');
  const [isSaving, setIsSaving] = useState(false);

  // --- Phase 30b: コンタクト追加モーダル ---
  const [showAddModal, setShowAddModal] = useState(false);

  // --- Phase 34: 詳細パネルタブ・活動履歴・組織・プロジェクト ---
  const [detailTab, setDetailTab] = useState<'info' | 'activities'>('info');
  const [activities, setActivities] = useState<Activity[]>([]);
  const [isLoadingActivities, setIsLoadingActivities] = useState(false);
  const [organizations, setOrganizations] = useState<OrgOption[]>([]);
  const [projects, setProjects] = useState<ProjectOption[]>([]);
  const [orgName, setOrgName] = useState('');
  const [showProjectAdd, setShowProjectAdd] = useState(false);
  const [selectedProjectToAdd, setSelectedProjectToAdd] = useState('');

  // --- Phase 35: 重複検出・マージ ---
  const [duplicateGroups, setDuplicateGroups] = useState<DuplicateGroup[]>([]);
  const [showMergeModal, setShowMergeModal] = useState(false);
  const [isMerging, setIsMerging] = useState(false);

  // --- Phase 35: チャンネル追加 ---
  const [showChannelAdd, setShowChannelAdd] = useState(false);
  const [newChannelType, setNewChannelType] = useState<'email' | 'slack' | 'chatwork'>('email');
  const [newChannelAddress, setNewChannelAddress] = useState('');
  const [isAddingChannel, setIsAddingChannel] = useState(false);

  // --- Phase 35: 連絡先結合 ---
  const [showLinkModal, setShowLinkModal] = useState(false);
  const [linkSearch, setLinkSearch] = useState('');
  const [isLinking, setIsLinking] = useState(false);

  // --- ブロックリスト関連state ---
  const [blocklist, setBlocklist] = useState<BlocklistEntry[]>([]);
  const [blocklistLoading, setBlocklistLoading] = useState(false);

  // ========================================
  // コンタクト取得
  // ========================================
  // Phase 29: debouncedSearch を使用してAPIコールを抑制
  const fetchContacts = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const params = new URLSearchParams();
      if (debouncedSearch) params.set('search', debouncedSearch);
      if (filterRelationship !== 'all') params.set('relationship', filterRelationship);
      if (filterChannel !== 'all') params.set('channel', filterChannel);

      const res = await fetch(`/api/contacts?${params}`);
      const data = await res.json();
      if (data.success) {
        setContacts(data.data);
        setStats(data.stats);
      } else {
        setError(data.error || '取得に失敗しました');
      }
    } catch {
      setError('通信エラーが発生しました');
    } finally {
      setIsLoading(false);
    }
  }, [debouncedSearch, filterRelationship, filterChannel]);

  useEffect(() => {
    fetchContacts();
  }, [fetchContacts]);

  // ========================================
  // ブロックリスト取得
  // ========================================
  const fetchBlocklist = useCallback(async () => {
    setBlocklistLoading(true);
    try {
      const res = await fetch('/api/inbox/blocklist');
      const data = await res.json();
      if (data.success) {
        setBlocklist(data.data || []);
      }
    } catch {
      // エラーは無視
    } finally {
      setBlocklistLoading(false);
    }
  }, []);

  useEffect(() => {
    if (activeTab === 'blocklist') {
      fetchBlocklist();
    }
  }, [activeTab, fetchBlocklist]);

  // ========================================
  // Phase 34: 組織・プロジェクト一覧取得
  // ========================================
  const fetchOrgAndProjects = useCallback(async () => {
    try {
      const [orgRes, projRes] = await Promise.all([
        fetch('/api/organizations'),
        fetch('/api/projects'),
      ]);
      const orgData = await orgRes.json();
      const projData = await projRes.json();
      if (orgData.success) setOrganizations((orgData.data || []).map((o: { id: string; name: string }) => ({ id: o.id, name: o.name })));
      if (projData.success) setProjects((projData.data || []).map((p: { id: string; name: string }) => ({ id: p.id, name: p.name })));
    } catch { /* エラーは無視 */ }
  }, []);

  useEffect(() => { fetchOrgAndProjects(); }, [fetchOrgAndProjects]);

  // ========================================
  // Phase 34: 活動履歴取得
  // ========================================
  const fetchActivities = useCallback(async (contactId: string) => {
    setIsLoadingActivities(true);
    try {
      const res = await fetch(`/api/contacts/${contactId}/activities`);
      const data = await res.json();
      if (data.success) setActivities(data.data || []);
    } catch { setActivities([]); }
    finally { setIsLoadingActivities(false); }
  }, []);

  // ========================================
  // コンタクト選択時に編集フィールドを初期化
  // ========================================
  useEffect(() => {
    if (selectedContact) {
      setEditCompany(selectedContact.companyName || '');
      setEditDepartment(selectedContact.department || '');
      setEditNotes(selectedContact.notes || '');
      setDetailTab('info');
      setActivities([]);
      setShowChannelAdd(false);
      setNewChannelAddress('');
      // Phase 34: 組織名を取得
      const org = organizations.find((o) => o.id === selectedContact.organization_id);
      setOrgName(org?.name || '');
    }
  }, [selectedContact, organizations]);

  // ========================================
  // 関係タイプ更新
  // ========================================
  const updateRelationship = async (contact: Contact, newType: string) => {
    try {
      const res = await fetch('/api/contacts', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: contact.id, address: contact.address, name: contact.name,
          relationshipType: newType, confirmed: true,
          mainChannel: contact.mainChannel, messageCount: contact.messageCount, lastContactAt: contact.lastContactAt,
        }),
      });
      const data = await res.json();
      if (data.success) {
        setContacts((prev) =>
          prev.map((c) => c.id === contact.id ? { ...c, relationshipType: newType, confirmed: true, id: data.data?.id || c.id } : c)
        );
        setEditingId(null);
      }
    } catch (err) {
      console.error('更新エラー:', err);
    }
  };

  // ========================================
  // コンテキスト情報保存（会社名・部署名・メモ）
  // ========================================
  const saveContactDetails = async () => {
    if (!selectedContact) return;
    setIsSaving(true);
    try {
      const res = await fetch('/api/contacts', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: selectedContact.id,
          address: selectedContact.address,
          name: selectedContact.name,
          companyName: editCompany,
          department: editDepartment,
          notes: editNotes,
          mainChannel: selectedContact.mainChannel,
          messageCount: selectedContact.messageCount,
          lastContactAt: selectedContact.lastContactAt,
        }),
      });
      const data = await res.json();
      if (data.success) {
        // ローカルstateを更新
        const newId = data.data?.id || selectedContact.id;
        setContacts((prev) =>
          prev.map((c) => c.id === selectedContact.id
            ? { ...c, id: newId, companyName: editCompany, department: editDepartment, notes: editNotes }
            : c
          )
        );
        setSelectedContact((prev) => prev ? { ...prev, id: newId, companyName: editCompany, department: editDepartment, notes: editNotes } : null);
        setActionResult({ type: 'success', text: 'コンタクト情報を保存しました' });
      } else {
        setActionResult({ type: 'error', text: '保存に失敗しました' });
      }
    } catch {
      setActionResult({ type: 'error', text: '通信エラー' });
    } finally {
      setIsSaving(false);
    }
    setTimeout(() => setActionResult(null), 3000);
  };

  // ========================================
  // ブロック追加（コンタクトから）
  // ========================================
  const blockContact = async (contact: Contact, matchType: 'exact' | 'domain') => {
    const address = matchType === 'domain'
      ? (contact.address?.split('@')[1] || '')
      : (contact.address || '');
    if (!address) return;

    try {
      const res = await fetch('/api/inbox/blocklist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ address, matchType, reason: 'コンタクトページからブロック' }),
      });
      const data = await res.json();
      if (data.success) {
        setActionResult({ type: 'success', text: `${address} をブロックしました` });
        setSelectedContact(null);
        fetchBlocklist();
      } else {
        setActionResult({ type: 'error', text: 'ブロックに失敗しました' });
      }
    } catch {
      setActionResult({ type: 'error', text: '通信エラー' });
    }
    setTimeout(() => setActionResult(null), 3000);
  };

  // ========================================
  // ブロック解除
  // ========================================
  const unblockEntry = async (entry: BlocklistEntry) => {
    try {
      const res = await fetch(`/api/inbox/blocklist?id=${entry.id}`, { method: 'DELETE' });
      const data = await res.json();
      if (data.success) {
        setBlocklist((prev) => prev.filter((b) => b.id !== entry.id));
        setActionResult({ type: 'success', text: `${entry.address} のブロックを解除しました` });
      } else {
        setActionResult({ type: 'error', text: '解除に失敗しました' });
      }
    } catch {
      setActionResult({ type: 'error', text: '通信エラー' });
    }
    setTimeout(() => setActionResult(null), 3000);
  };

  // ========================================
  // エンリッチ（自動取得）実行
  // ========================================
  const runEnrich = async () => {
    setIsEnriching(true);
    setEnrichResult(null);
    try {
      const res = await fetch('/api/contacts/enrich', { method: 'POST' });
      const data = await res.json();
      if (data.success) {
        setEnrichResult({ enriched: data.enriched, details: data.details || [] });
        setActionResult({ type: 'success', text: `${data.enriched}件のコンタクト情報を自動取得しました（Slack: ${data.slackProfilesFound}件, Chatwork: ${data.chatworkProfilesFound}件のプロフィール参照）` });
        // コンタクト一覧を再読み込み
        fetchContacts();
      } else {
        setActionResult({ type: 'error', text: data.error || '自動取得に失敗しました' });
      }
    } catch {
      setActionResult({ type: 'error', text: '通信エラー' });
    } finally {
      setIsEnriching(false);
    }
    setTimeout(() => setActionResult(null), 5000);
  };

  // ========================================
  // Phase 34: プロジェクトメンバー追加
  // ========================================
  const addToProject = async () => {
    if (!selectedContact || !selectedProjectToAdd) return;
    try {
      const res = await fetch('/api/project-members', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ projectId: selectedProjectToAdd, contactId: selectedContact.id, role: 'member' }),
      });
      const data = await res.json();
      if (data.success) {
        setActionResult({ type: 'success', text: 'プロジェクトに追加しました' });
        setShowProjectAdd(false);
        setSelectedProjectToAdd('');
      } else {
        setActionResult({ type: 'error', text: data.error || '追加に失敗しました' });
      }
    } catch { setActionResult({ type: 'error', text: '通信エラー' }); }
    setTimeout(() => setActionResult(null), 3000);
  };

  // ========================================
  // Phase 35: 重複候補を取得
  // ========================================
  const fetchDuplicates = useCallback(async () => {
    try {
      const res = await fetch('/api/contacts/duplicates');
      const data = await res.json();
      if (data.success) {
        setDuplicateGroups(data.data?.groups || []);
      }
    } catch { /* エラーは無視 */ }
  }, []);

  useEffect(() => { fetchDuplicates(); }, [fetchDuplicates]);

  // Phase 35: チャンネル追加
  const addChannel = async () => {
    if (!selectedContact || !newChannelAddress.trim()) return;
    setIsAddingChannel(true);
    try {
      const res = await fetch(`/api/contacts/${selectedContact.id}/channels`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ channel: newChannelType, address: newChannelAddress.trim() }),
      });
      const data = await res.json();
      if (data.success) {
        setActionResult({ type: 'success', text: 'チャンネルを追加しました' });
        setNewChannelAddress('');
        setShowChannelAdd(false);
        // activeChannelsをローカル更新
        const newAc = { channel: newChannelType, name: newChannelAddress.trim() };
        setSelectedContact((prev) => prev ? {
          ...prev,
          activeChannels: [...(prev.activeChannels || []), newAc],
        } : null);
        // コンタクト一覧も再取得
        fetchContacts();
      } else {
        setActionResult({ type: 'error', text: data.error || 'チャンネル追加に失敗しました' });
      }
    } catch {
      setActionResult({ type: 'error', text: '通信エラー' });
    } finally {
      setIsAddingChannel(false);
    }
    setTimeout(() => setActionResult(null), 3000);
  };

  // Phase 35: 連絡先結合（詳細パネルから）
  const executeLinkMerge = async (targetContactId: string) => {
    if (!selectedContact) return;
    const targetContact = contacts.find((c) => c.id === targetContactId);
    const targetName = targetContact?.name || targetContactId;
    if (!confirm(`「${targetName}」さんを「${selectedContact.name}」に統合します。「${targetName}」さんのレコードは削除されます。よろしいですか？`)) return;
    setIsLinking(true);
    try {
      const res = await fetch('/api/contacts/merge', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ primaryId: selectedContact.id, mergeIds: [targetContactId] }),
      });
      const data = await res.json();
      if (data.success) {
        setActionResult({ type: 'success', text: `${targetName}さんを統合しました` });
        setShowLinkModal(false);
        setLinkSearch('');
        fetchContacts();
        fetchDuplicates();
      } else {
        setActionResult({ type: 'error', text: data.error || '統合に失敗しました' });
      }
    } catch {
      setActionResult({ type: 'error', text: '通信エラー' });
    } finally {
      setIsLinking(false);
    }
    setTimeout(() => setActionResult(null), 3000);
  };

  // Phase 35: マージ実行
  const executeMerge = async (primaryId: string, mergeIds: string[]) => {
    setIsMerging(true);
    try {
      const res = await fetch('/api/contacts/merge', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ primaryId, mergeIds }),
      });
      const data = await res.json();
      if (data.success) {
        setActionResult({ type: 'success', text: `${data.data.mergedCount}件のコンタクトを統合しました` });
        fetchContacts();
        fetchDuplicates();
      } else {
        setActionResult({ type: 'error', text: data.error || '統合に失敗しました' });
      }
    } catch {
      setActionResult({ type: 'error', text: '通信エラー' });
    } finally {
      setIsMerging(false);
    }
    setTimeout(() => setActionResult(null), 3000);
  };

  return (
    <div className="flex flex-col h-screen bg-white">
      <Header />
      <div className="flex-1 overflow-hidden flex flex-col">
        {/* ヘッダー */}
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <Users className="w-5 h-5 text-slate-600" />
              <h1 className="text-lg font-bold text-slate-900">コンタクト</h1>
            </div>
            {/* Phase 30b: コンタクト追加ボタン */}
            <div className="flex items-center gap-2">
              <button
                onClick={() => setShowAddModal(true)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors"
              >
                <UserPlus className="w-3.5 h-3.5" />
                追加
              </button>
            <button
              onClick={runEnrich}
              disabled={isEnriching}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-blue-600 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 disabled:opacity-50 transition-colors"
              title="Slack/Chatworkのプロフィール、メール署名、会話パターンから自動取得"
            >
              {isEnriching ? (
                <>
                  <span className="animate-spin">&#8987;</span>
                  取得中...
                </>
              ) : (
                <>
                  <Search className="w-3.5 h-3.5" />
                  プロフィール自動取得
                </>
              )}
            </button>
            {/* Phase 35: 重複統合ボタン */}
            {duplicateGroups.length > 0 && (
              <button
                onClick={() => setShowMergeModal(true)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-orange-600 bg-orange-50 border border-orange-200 rounded-lg hover:bg-orange-100 transition-colors"
              >
                <GitMerge className="w-3.5 h-3.5" />
                重複を統合
                <span className="bg-orange-200 text-orange-700 px-1.5 py-0.5 rounded-full text-[10px] font-bold">{duplicateGroups.length}</span>
              </button>
            )}
            </div>
          </div>

          {/* タブ切り替え */}
          <div className="flex gap-1 mb-3">
            <button
              onClick={() => setActiveTab('contacts')}
              className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                activeTab === 'contacts' ? 'bg-blue-600 text-white' : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
              }`}
            >
              <Users className="w-3.5 h-3.5" />
              コンタクト一覧
              {stats && <span className="ml-1 opacity-80">{stats.total}</span>}
            </button>
            <button
              onClick={() => setActiveTab('blocklist')}
              className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                activeTab === 'blocklist' ? 'bg-red-600 text-white' : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
              }`}
            >
              <Shield className="w-3.5 h-3.5" />
              ブロックリスト
              {blocklist.length > 0 && <span className="ml-1 opacity-80">{blocklist.length}</span>}
            </button>
          </div>

          {/* コンタクトタブ: 統計バッジ + 検索 */}
          {activeTab === 'contacts' && (
            <>
              {stats && (
                <div className="flex gap-2 mb-3">
                  {Object.entries(RELATIONSHIP_LABELS).map(([key, { label, color }]) => {
                    const count = (stats.byRelationship as Record<string, number>)[key] || 0;
                    if (count === 0 && key !== 'unknown') return null;
                    return (
                      <button
                        key={key}
                        onClick={() => setFilterRelationship(filterRelationship === key ? 'all' : key)}
                        className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium transition-colors ${
                          filterRelationship === key ? 'ring-2 ring-offset-1 ring-blue-400' : ''
                        } ${color}`}
                      >
                        {label} <span className="font-bold">{count}</span>
                      </button>
                    );
                  })}
                </div>
              )}
              <div className="flex gap-2">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                  <input
                    type="text"
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    placeholder="名前・アドレス・会社名で検索..."
                    className="w-full pl-9 pr-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>
                <select
                  value={filterChannel}
                  onChange={(e) => setFilterChannel(e.target.value)}
                  className="px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <option value="all">全チャネル</option>
                  <option value="email">Gmail</option>
                  <option value="slack">Slack</option>
                  <option value="chatwork">Chatwork</option>
                </select>
              </div>
            </>
          )}
        </div>

        {/* アクション結果バナー */}
        {actionResult && (
          <div className={`mx-6 mt-2 px-3 py-2 rounded-lg text-xs font-medium ${
            actionResult.type === 'success' ? 'bg-green-50 text-green-700 border border-green-200' : 'bg-red-50 text-red-700 border border-red-200'
          }`}>
            {actionResult.type === 'success' ? '✅' : '❌'} {actionResult.text}
          </div>
        )}

        {/* エンリッチ結果の詳細 */}
        {enrichResult && enrichResult.details.length > 0 && (
          <div className="mx-6 mt-2 px-3 py-2 bg-blue-50 border border-blue-200 rounded-lg">
            <div className="flex items-center justify-between mb-1">
              <span className="text-xs font-semibold text-blue-700">自動取得結果: {enrichResult.enriched}件</span>
              <button onClick={() => setEnrichResult(null)} className="text-blue-400 hover:text-blue-600">
                <X className="w-3.5 h-3.5" />
              </button>
            </div>
            <div className="max-h-32 overflow-y-auto">
              {enrichResult.details.map((d, i) => (
                <div key={i} className="text-[11px] text-blue-600 py-0.5">
                  <strong>{d.name}</strong>: {d.updates.join(' / ')}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Phase 35: 重複候補バナー */}
        {duplicateGroups.length > 0 && !showMergeModal && (
          <div className="mx-6 mt-2 px-3 py-2 bg-orange-50 border border-orange-200 rounded-lg flex items-center justify-between">
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-orange-500" />
              <span className="text-xs font-medium text-orange-700">
                {duplicateGroups.length}件の重複候補があります（合計{duplicateGroups.reduce((sum, g) => sum + g.contacts.length, 0)}件のコンタクト）
              </span>
            </div>
            <button
              onClick={() => setShowMergeModal(true)}
              className="text-xs font-medium text-orange-600 hover:text-orange-800 underline"
            >
              確認する
            </button>
          </div>
        )}

        {/* コンテンツエリア: テーブル + 詳細パネルの横並び */}
        {activeTab === 'contacts' && (
          <div className="flex-1 overflow-hidden flex">
            {/* テーブル部分 */}
            <div className={`overflow-y-auto ${selectedContact ? 'w-1/2 border-r border-slate-200' : 'w-full'} transition-all`}>
              {isLoading ? (
                <div className="flex items-center justify-center h-64 text-slate-400">
                  <div className="text-center">
                    <div className="animate-spin text-2xl mb-2">&#8987;</div>
                    <p className="text-sm">読み込み中...</p>
                  </div>
                </div>
              ) : error ? (
                <div className="p-6 text-center text-red-500">{error}</div>
              ) : contacts.length === 0 ? (
                <div className="flex items-center justify-center h-64 text-slate-400">
                  <div className="text-center">
                    <Users className="w-12 h-12 mx-auto mb-3 text-slate-300" />
                    <p className="text-sm">コンタクトがありません</p>
                    <p className="text-xs mt-1">インボックスでメッセージを受信すると自動的に追加されます</p>
                  </div>
                </div>
              ) : (
                <table className="w-full">
                  <thead className="bg-slate-50 sticky top-0 z-10">
                    <tr className="border-b border-slate-200">
                      <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">名前</th>
                      <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">会社</th>
                      <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">チャネル</th>
                      <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">関係</th>
                      <th className="text-right text-xs font-semibold text-slate-500 px-4 py-3">件数</th>
                      <th className="text-right text-xs font-semibold text-slate-500 px-4 py-3">最終連絡</th>
                    </tr>
                  </thead>
                  <tbody>
                    {contacts.map((contact) => (
                      <tr
                        key={contact.id}
                        onClick={() => setSelectedContact(selectedContact?.id === contact.id ? null : contact)}
                        className={`border-b border-slate-100 hover:bg-blue-50 cursor-pointer transition-colors ${
                          selectedContact?.id === contact.id ? 'bg-blue-50' : ''
                        }`}
                      >
                        <td className="px-4 py-3">
                          <div className="flex items-center gap-3">
                            <div className={`w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold shrink-0 ${getAvatarColor(contact.name)}`}>
                              {getInitials(contact.name)}
                            </div>
                            <div className="min-w-0">
                              <div className="text-sm font-medium text-slate-900 truncate">{contact.name}</div>
                              <div className="text-[10px] text-slate-400 truncate">{contact.address || '-'}</div>
                            </div>
                          </div>
                        </td>
                        <td className="px-4 py-3">
                          <span className="text-xs text-slate-600 truncate block max-w-[120px]">
                            {contact.companyName || '-'}
                          </span>
                        </td>
                        <td className="px-4 py-3">
                          <div className="flex items-center gap-1">
                            {/* Phase 35: contact_channels(DB)からチャンネル種別ごとにアイコン表示 */}
                            {(() => {
                              const types = new Set<string>();
                              if (contact.channels && contact.channels.length > 0) {
                                for (const ch of contact.channels) types.add(ch.channel);
                              }
                              // channels が空の場合は allChannels にフォールバック
                              if (types.size === 0) {
                                for (const ch of (contact.allChannels || [contact.mainChannel])) types.add(ch);
                              }
                              return Array.from(types).map((ch) => (
                                CHANNEL_ICONS[ch] ? (
                                  <Image key={ch} src={CHANNEL_ICONS[ch]} alt={ch} width={16} height={16} title={CHANNEL_LABELS[ch]} />
                                ) : (
                                  <Mail key={ch} className="w-4 h-4 text-slate-400" />
                                )
                              ));
                            })()}
                            {contact.visibility === 'shared' && (
                              <span className="text-[9px] bg-blue-50 text-blue-500 px-1 rounded" title="チーム共有">共有</span>
                            )}
                          </div>
                        </td>
                        <td className="px-4 py-3" onClick={(e) => e.stopPropagation()}>
                          {editingId === contact.id ? (
                            <div className="flex items-center gap-1">
                              <select
                                value={editRelationship}
                                onChange={(e) => setEditRelationship(e.target.value)}
                                className="text-xs border border-slate-300 rounded px-1.5 py-1 focus:outline-none focus:ring-1 focus:ring-blue-500"
                              >
                                <option value="internal">自社メンバー</option>
                                <option value="client">クライアント</option>
                                <option value="partner">パートナー</option>
                                <option value="unknown">未分類</option>
                              </select>
                              <button onClick={() => updateRelationship(contact, editRelationship)} className="p-0.5 text-green-600 hover:text-green-800">
                                <Check className="w-3.5 h-3.5" />
                              </button>
                              <button onClick={() => setEditingId(null)} className="p-0.5 text-slate-400 hover:text-slate-600">
                                <X className="w-3.5 h-3.5" />
                              </button>
                            </div>
                          ) : (
                            <button
                              onClick={() => { setEditingId(contact.id); setEditRelationship(contact.relationshipType); }}
                              className="inline-flex items-center gap-1 group"
                            >
                              <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-medium ${
                                RELATIONSHIP_LABELS[contact.relationshipType]?.color || RELATIONSHIP_LABELS.unknown.color
                              }`}>
                                {RELATIONSHIP_LABELS[contact.relationshipType]?.label || '未分類'}
                              </span>
                              <Edit2 className="w-3 h-3 text-slate-300 opacity-0 group-hover:opacity-100 transition-opacity" />
                            </button>
                          )}
                        </td>
                        <td className="px-4 py-3 text-right">
                          <span className="text-sm text-slate-700 font-medium">{contact.messageCount}</span>
                        </td>
                        <td className="px-4 py-3 text-right">
                          <span className="text-xs text-slate-400">{formatDate(contact.lastContactAt)}</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>

            {/* ========================================
                選択時の詳細パネル（右サイド）Phase 34: 強化版
                ======================================== */}
            {selectedContact && (
              <div className="w-1/2 overflow-y-auto bg-slate-50 p-5">
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className={`w-12 h-12 rounded-full flex items-center justify-center text-white text-lg font-bold shrink-0 ${getAvatarColor(selectedContact.name)}`}>
                      {getInitials(selectedContact.name)}
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <h3 className="text-base font-bold text-slate-900">{selectedContact.name}</h3>
                        {/* Phase 34: チームメンバーバッジ */}
                        {selectedContact.is_team_member && (
                          <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium bg-blue-100 text-blue-700">
                            <Users className="w-3 h-3" />
                            チーム
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-slate-500">{selectedContact.address || 'アドレス未取得'}</p>
                      {/* Phase 34: 所属組織表示 */}
                      {orgName && (
                        <div className="flex items-center gap-1 mt-0.5">
                          <Building2 className="w-3 h-3 text-slate-400" />
                          <span className="text-xs text-slate-500">{orgName}</span>
                        </div>
                      )}
                    </div>
                  </div>
                  <button onClick={() => setSelectedContact(null)} className="text-slate-400 hover:text-slate-600">
                    <X className="w-5 h-5" />
                  </button>
                </div>

                {/* 基本情報 */}
                <div className="flex items-center gap-4 mb-4 text-xs text-slate-500">
                  <span>やり取り: <strong className="text-slate-700">{selectedContact.messageCount}件</strong></span>
                  <span>最終: <strong className="text-slate-700">{formatDate(selectedContact.lastContactAt)}</strong></span>
                  {selectedContact.visibility === 'shared' && (
                    <span className="inline-flex items-center gap-1 text-blue-600 bg-blue-50 px-2 py-0.5 rounded">
                      <Users className="w-3 h-3" />
                      チーム共有
                    </span>
                  )}
                </div>

                {/* Phase 34: タブ切り替え + Phase 35: 連絡先結合 */}
                <div className="flex items-center gap-1 mb-4">
                  <button
                    onClick={() => setDetailTab('info')}
                    className={`inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                      detailTab === 'info' ? 'bg-blue-600 text-white' : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
                    }`}
                  >
                    <Edit2 className="w-3 h-3" />
                    基本情報
                  </button>
                  <button
                    onClick={() => {
                      setDetailTab('activities');
                      if (activities.length === 0) fetchActivities(selectedContact.id);
                    }}
                    className={`inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                      detailTab === 'activities' ? 'bg-blue-600 text-white' : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
                    }`}
                  >
                    <Clock className="w-3 h-3" />
                    活動履歴
                  </button>
                  {/* Phase 35: 連絡先結合ボタン（タブと同じスタイル） */}
                  <button
                    onClick={() => { setShowLinkModal(true); setLinkSearch(''); }}
                    className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium bg-white text-slate-600 hover:bg-slate-100 border border-slate-200 transition-colors"
                  >
                    <Link2 className="w-3 h-3" />
                    連絡先結合
                  </button>
                </div>

                {/* ========== 基本情報タブ ========== */}
                {detailTab === 'info' && (
                  <>
                    {/* やり取りチャネル一覧 + Phase 35: チャンネル追加 */}
                    <div className="mb-4">
                      <div className="flex items-center justify-between mb-2">
                        <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-500">
                          <MessageSquare className="w-3.5 h-3.5" />
                          やり取りチャネル
                        </label>
                        <button
                          onClick={() => { setShowChannelAdd(!showChannelAdd); setNewChannelAddress(''); }}
                          className="p-1 text-slate-400 hover:text-blue-600 transition-colors"
                          title="チャンネル追加"
                        >
                          <Plus className="w-3.5 h-3.5" />
                        </button>
                      </div>
                      {/* Phase 35: activeChannels + contact_channels(DB) を統合表示 */}
                      {(() => {
                        // Phase 35: 数字ID/Slack IDを名前に変換するヘルパー
                        const isNumericId = (s: string) => /^\d+$/.test(s);
                        const isSlackId = (s: string) => /^U[A-Z0-9]+$/i.test(s);
                        const resolveLabel = (raw: string): string => {
                          // 自分自身のaddressと一致 → 「マイチャット」
                          if (raw === selectedContact.address) return 'マイチャット';
                          // 数字のみ or Slack ID → 他コンタクトから名前を探す
                          if (isNumericId(raw) || isSlackId(raw)) {
                            const match = contacts.find((c) => c.id !== selectedContact.id && c.address === raw);
                            if (match) return match.name;
                          }
                          return raw;
                        };

                        // contact_channels(DB)とactiveChannels(メッセージ由来)を統合
                        const seen = new Set<string>();
                        const merged: { channel: string; label: string }[] = [];
                        // DB contact_channels を優先表示
                        if (selectedContact.channels && selectedContact.channels.length > 0) {
                          for (const ch of selectedContact.channels) {
                            const key = `${ch.channel}::${ch.address}`;
                            if (!seen.has(key)) {
                              seen.add(key);
                              merged.push({ channel: ch.channel, label: resolveLabel(ch.address) });
                            }
                          }
                        }
                        // activeChannels で未登録のものも追加
                        if (selectedContact.activeChannels) {
                          for (const ac of selectedContact.activeChannels) {
                            const key = `${ac.channel}::${ac.name}`;
                            if (!seen.has(key)) {
                              seen.add(key);
                              merged.push({ channel: ac.channel, label: resolveLabel(ac.name) });
                            }
                          }
                        }
                        if (merged.length === 0) return null;
                        return (
                          <div className="flex flex-wrap gap-1.5 mb-2">
                            {merged.map((item, i) => (
                              <span key={i} className="inline-flex items-center gap-1.5 text-xs bg-white border border-slate-200 px-2.5 py-1 rounded-lg">
                                {CHANNEL_ICONS[item.channel] && (
                                  <Image src={CHANNEL_ICONS[item.channel]} alt={item.channel} width={14} height={14} />
                                )}
                                {item.label}
                              </span>
                            ))}
                          </div>
                        );
                      })()}
                      {/* Phase 35: チャンネル追加フォーム */}
                      {showChannelAdd && (
                        <div className="flex gap-2 items-end">
                          <select
                            value={newChannelType}
                            onChange={(e) => setNewChannelType(e.target.value as 'email' | 'slack' | 'chatwork')}
                            className="px-2 py-1.5 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          >
                            <option value="email">Email</option>
                            <option value="slack">Slack</option>
                            <option value="chatwork">Chatwork</option>
                          </select>
                          <input
                            type="text"
                            value={newChannelAddress}
                            onChange={(e) => setNewChannelAddress(e.target.value)}
                            placeholder="アドレス / ID"
                            className="flex-1 px-2 py-1.5 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          />
                          <button
                            onClick={addChannel}
                            disabled={isAddingChannel || !newChannelAddress.trim()}
                            className="px-3 py-1.5 text-xs font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors"
                          >
                            {isAddingChannel ? '...' : '追加'}
                          </button>
                        </div>
                      )}
                    </div>

                    {/* 会社名・部署名 */}
                    <div className="space-y-3 mb-4">
                      <div>
                        <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-500 mb-1">
                          <Building2 className="w-3.5 h-3.5" />
                          会社名
                        </label>
                        <input
                          type="text"
                          value={editCompany}
                          onChange={(e) => setEditCompany(e.target.value)}
                          placeholder="例: 株式会社ネクストステージ"
                          className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                        />
                      </div>
                      <div>
                        <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-500 mb-1">
                          <Users className="w-3.5 h-3.5" />
                          部署名
                        </label>
                        <input
                          type="text"
                          value={editDepartment}
                          onChange={(e) => setEditDepartment(e.target.value)}
                          placeholder="例: 開発部"
                          className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                        />
                      </div>
                    </div>

                    {/* メモ / AIコンテキスト */}
                    <div className="mb-4">
                      <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-500 mb-1">
                        <Edit2 className="w-3.5 h-3.5" />
                        メモ / AIコンテキスト
                      </label>
                      <p className="text-[10px] text-slate-400 mb-1.5">
                        ここに書いた内容は、将来のAI返信下書きのトーン・文体に反映されます
                      </p>
                      <textarea
                        value={editNotes}
                        onChange={(e) => setEditNotes(e.target.value)}
                        placeholder="例: 古くからの付き合い。カジュアルな口調でOK。技術的な話が多い。"
                        rows={3}
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white resize-none"
                      />
                    </div>

                    {/* 保存ボタン */}
                    <button
                      onClick={saveContactDetails}
                      disabled={isSaving}
                      className="inline-flex items-center gap-1.5 px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors"
                    >
                      <Save className="w-4 h-4" />
                      {isSaving ? '保存中...' : '保存'}
                    </button>

                    {/* Phase 34: プロジェクト紐付け */}
                    <div className="mt-4 pt-4 border-t border-slate-200">
                      <div className="flex items-center justify-between mb-2">
                        <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-500">
                          <FolderOpen className="w-3.5 h-3.5" />
                          プロジェクト紐付け
                        </label>
                        <button
                          onClick={() => setShowProjectAdd(!showProjectAdd)}
                          className="p-1 text-slate-400 hover:text-blue-600 transition-colors"
                        >
                          <Plus className="w-3.5 h-3.5" />
                        </button>
                      </div>
                      {showProjectAdd && projects.length > 0 && (
                        <div className="flex gap-2 mb-2">
                          <select
                            value={selectedProjectToAdd}
                            onChange={(e) => setSelectedProjectToAdd(e.target.value)}
                            className="flex-1 px-2 py-1.5 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                          >
                            <option value="">プロジェクトを選択</option>
                            {projects.map((p) => (
                              <option key={p.id} value={p.id}>{p.name}</option>
                            ))}
                          </select>
                          <button
                            onClick={addToProject}
                            disabled={!selectedProjectToAdd}
                            className="px-3 py-1.5 text-xs font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors"
                          >
                            追加
                          </button>
                        </div>
                      )}
                      {projects.length === 0 && showProjectAdd && (
                        <p className="text-xs text-slate-400 mb-2">プロジェクトがありません。ビジネスログから作成してください。</p>
                      )}
                    </div>

                    {/* ブロックボタン（メールコンタクトのみ） */}
                    {selectedContact.mainChannel === 'email' && selectedContact.address && (
                      <div className="mt-4 pt-4 border-t border-slate-200">
                        <p className="text-xs font-semibold text-slate-500 mb-2">ブロック操作</p>
                        <div className="flex gap-2">
                          <button
                            onClick={() => blockContact(selectedContact, 'exact')}
                            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-red-600 bg-red-50 border border-red-200 rounded-lg hover:bg-red-100 transition-colors"
                          >
                            <Shield className="w-3.5 h-3.5" />
                            このアドレスをブロック
                          </button>
                          {selectedContact.address.includes('@') && (
                            <button
                              onClick={() => blockContact(selectedContact, 'domain')}
                              className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-orange-600 bg-orange-50 border border-orange-200 rounded-lg hover:bg-orange-100 transition-colors"
                            >
                              <Shield className="w-3.5 h-3.5" />
                              @{selectedContact.address.split('@')[1]} をブロック
                            </button>
                          )}
                        </div>
                      </div>
                    )}
                  </>
                )}

                {/* ========== Phase 34: 活動履歴タブ ========== */}
                {detailTab === 'activities' && (
                  <div>
                    {isLoadingActivities ? (
                      <div className="flex items-center justify-center h-32 text-slate-400">
                        <div className="text-center">
                          <div className="animate-spin text-xl mb-1">&#8987;</div>
                          <p className="text-xs">読み込み中...</p>
                        </div>
                      </div>
                    ) : activities.length === 0 ? (
                      <div className="flex items-center justify-center h-32 text-slate-400">
                        <div className="text-center">
                          <Clock className="w-8 h-8 mx-auto mb-2 text-slate-300" />
                          <p className="text-xs">活動履歴がありません</p>
                        </div>
                      </div>
                    ) : (
                      <div className="space-y-2">
                        {activities.map((activity) => (
                          <div key={activity.id} className="p-3 bg-white border border-slate-200 rounded-lg">
                            <div className="flex items-center gap-2 mb-1">
                              <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium ${
                                activity.type === 'event'
                                  ? 'bg-blue-100 text-blue-700'
                                  : 'bg-slate-100 text-slate-600'
                              }`}>
                                {activity.type === 'event' ? activity.eventType : activity.eventType}
                              </span>
                              <span className="text-[10px] text-slate-400">{formatDate(activity.timestamp)}</span>
                            </div>
                            <p className="text-sm font-medium text-slate-900 truncate">{activity.title}</p>
                            {activity.content && (
                              <p className="text-xs text-slate-500 mt-0.5 line-clamp-2">{activity.content}</p>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* ========================================
            ブロックリストタブ
            ======================================== */}
        {activeTab === 'blocklist' && (
          <div className="flex-1 overflow-y-auto">
            {blocklistLoading ? (
              <div className="flex items-center justify-center h-64 text-slate-400">
                <div className="text-center">
                  <div className="animate-spin text-2xl mb-2">&#8987;</div>
                  <p className="text-sm">読み込み中...</p>
                </div>
              </div>
            ) : blocklist.length === 0 ? (
              <div className="flex items-center justify-center h-64 text-slate-400">
                <div className="text-center">
                  <Shield className="w-12 h-12 mx-auto mb-3 text-slate-300" />
                  <p className="text-sm">ブロックリストは空です</p>
                  <p className="text-xs mt-1">コンタクト一覧から不要な送信者をブロックできます</p>
                </div>
              </div>
            ) : (
              <table className="w-full">
                <thead className="bg-slate-50 sticky top-0 z-10">
                  <tr className="border-b border-slate-200">
                    <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">アドレス / ドメイン</th>
                    <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">種類</th>
                    <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">理由</th>
                    <th className="text-left text-xs font-semibold text-slate-500 px-4 py-3">ブロック日</th>
                    <th className="text-right text-xs font-semibold text-slate-500 px-4 py-3">操作</th>
                  </tr>
                </thead>
                <tbody>
                  {blocklist.map((entry) => (
                    <tr key={entry.id} className="border-b border-slate-100 hover:bg-slate-50">
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-2">
                          <Shield className="w-4 h-4 text-red-400" />
                          <span className="text-sm font-medium text-slate-900">
                            {entry.match_type === 'domain' ? `@${entry.address}` : entry.address}
                          </span>
                        </div>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-medium ${
                          entry.match_type === 'domain' ? 'bg-orange-100 text-orange-700' : 'bg-red-100 text-red-700'
                        }`}>
                          {entry.match_type === 'domain' ? 'ドメイン全体' : '個別アドレス'}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <span className="text-xs text-slate-500">{entry.reason || '-'}</span>
                      </td>
                      <td className="px-4 py-3">
                        <span className="text-xs text-slate-400">{formatDate(entry.created_at)}</span>
                      </td>
                      <td className="px-4 py-3 text-right">
                        <button
                          onClick={() => unblockEntry(entry)}
                          className="inline-flex items-center gap-1 px-2.5 py-1 text-xs font-medium text-slate-600 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 hover:border-slate-300 transition-colors"
                        >
                          <ShieldOff className="w-3.5 h-3.5" />
                          解除
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        )}
      </div>

      {/* Phase 30b: コンタクト追加モーダル */}
      <QuickAddContactModal
        isOpen={showAddModal}
        onClose={() => setShowAddModal(false)}
        onSaved={() => {
          fetchContacts();
          setActionResult({ type: 'success', text: 'コンタクトを追加しました' });
          setTimeout(() => setActionResult(null), 3000);
        }}
      />

      {/* Phase 35: 連絡先結合モーダル */}
      {showLinkModal && selectedContact && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
          <div className="bg-white rounded-lg shadow-xl w-full max-w-md mx-4 max-h-[70vh] flex flex-col">
            <div className="flex items-center justify-between px-5 py-4 border-b border-slate-200">
              <div className="flex items-center gap-2">
                <Link2 className="w-5 h-5 text-blue-500" />
                <h2 className="text-base font-bold text-slate-900">連絡先結合</h2>
              </div>
              <button onClick={() => setShowLinkModal(false)} className="text-slate-400 hover:text-slate-600">
                <X className="w-5 h-5" />
              </button>
            </div>
            <div className="px-5 py-3 border-b border-slate-200 bg-slate-50">
              <p className="text-xs text-slate-500 mb-2">
                「{selectedContact.name}」に統合するコンタクトを検索してください
              </p>
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input
                  type="text"
                  value={linkSearch}
                  onChange={(e) => setLinkSearch(e.target.value)}
                  placeholder="名前で検索..."
                  className="w-full pl-9 pr-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  autoFocus
                />
              </div>
            </div>
            <div className="flex-1 overflow-y-auto px-5 py-3">
              {(() => {
                const q = linkSearch.toLowerCase().trim();
                if (!q) return <p className="text-xs text-slate-400 text-center py-4">検索キーワードを入力してください</p>;
                const filtered = contacts.filter(
                  (c) => c.id !== selectedContact.id && c.name?.toLowerCase().includes(q)
                );
                if (filtered.length === 0) return <p className="text-xs text-slate-400 text-center py-4">該当するコンタクトがありません</p>;
                return (
                  <div className="space-y-1">
                    {filtered.slice(0, 20).map((c) => (
                      <div key={c.id} className="flex items-center justify-between p-2 rounded-lg hover:bg-slate-50 transition-colors">
                        <div className="flex items-center gap-2.5 min-w-0 flex-1">
                          <div className={`w-7 h-7 rounded-full flex items-center justify-center text-white text-[10px] font-bold shrink-0 ${getAvatarColor(c.name)}`}>
                            {getInitials(c.name)}
                          </div>
                          <div className="min-w-0">
                            <div className="text-sm font-medium text-slate-900 truncate">{c.name}</div>
                            <div className="flex items-center gap-1.5 text-[10px] text-slate-400">
                              {(c.allChannels || [c.mainChannel]).map((ch) => (
                                CHANNEL_ICONS[ch] ? (
                                  <Image key={ch} src={CHANNEL_ICONS[ch]} alt={ch} width={12} height={12} />
                                ) : null
                              ))}
                              {c.companyName && <span>{c.companyName}</span>}
                            </div>
                          </div>
                        </div>
                        <button
                          onClick={() => executeLinkMerge(c.id)}
                          disabled={isLinking}
                          className="shrink-0 ml-2 inline-flex items-center gap-1 px-2.5 py-1 text-[11px] font-medium text-blue-600 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 disabled:opacity-50 transition-colors"
                        >
                          <GitMerge className="w-3 h-3" />
                          統合
                        </button>
                      </div>
                    ))}
                  </div>
                );
              })()}
            </div>
            <div className="px-5 py-3 border-t border-slate-200 bg-slate-50 rounded-b-lg">
              <p className="text-[10px] text-slate-400">
                選択したコンタクトのチャネル・イベント・プロジェクトが「{selectedContact.name}」に移行され、元のレコードは削除されます。
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Phase 35: 重複統合モーダル */}
      {showMergeModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
          <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl mx-4 max-h-[80vh] flex flex-col">
            {/* モーダルヘッダー */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-slate-200">
              <div className="flex items-center gap-2">
                <GitMerge className="w-5 h-5 text-orange-500" />
                <h2 className="text-base font-bold text-slate-900">重複コンタクトの統合</h2>
                <span className="text-xs text-slate-500">{duplicateGroups.length}グループ</span>
              </div>
              <button onClick={() => setShowMergeModal(false)} className="text-slate-400 hover:text-slate-600">
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* モーダルコンテンツ */}
            <div className="flex-1 overflow-y-auto px-5 py-4 space-y-4">
              {duplicateGroups.length === 0 ? (
                <div className="text-center py-8 text-slate-400">
                  <Check className="w-10 h-10 mx-auto mb-2 text-green-400" />
                  <p className="text-sm">重複候補はありません</p>
                </div>
              ) : (
                duplicateGroups.map((group, gi) => (
                  <div key={gi} className="border border-slate-200 rounded-lg overflow-hidden">
                    <div className="bg-slate-50 px-4 py-2 border-b border-slate-200">
                      <span className="text-sm font-semibold text-slate-700">
                        &quot;{group.name}&quot; — {group.contacts.length}件の重複
                      </span>
                    </div>
                    <div className="divide-y divide-slate-100">
                      {group.contacts.map((dc, ci) => (
                        <div key={dc.id} className="px-4 py-3 flex items-center justify-between">
                          <div className="flex items-center gap-3 min-w-0 flex-1">
                            <div className={`w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold shrink-0 ${getAvatarColor(dc.name || '')}`}>
                              {getInitials(dc.name || '')}
                            </div>
                            <div className="min-w-0">
                              <div className="text-sm font-medium text-slate-900 truncate">{dc.name}</div>
                              <div className="flex items-center gap-2 text-[10px] text-slate-400">
                                {dc.company_name && <span>{dc.company_name}</span>}
                                {dc.main_channel && <span>{CHANNEL_LABELS[dc.main_channel] || dc.main_channel}</span>}
                                <span>メッセージ {dc.message_count || 0}件</span>
                                {dc.last_contact_at && <span>最終: {formatDate(dc.last_contact_at)}</span>}
                              </div>
                            </div>
                          </div>
                          <button
                            onClick={() => {
                              const mergeIds = group.contacts.filter((c) => c.id !== dc.id).map((c) => c.id);
                              if (confirm(`「${dc.name}」をメインとして、他の${mergeIds.length}件を統合します。よろしいですか？`)) {
                                executeMerge(dc.id, mergeIds);
                              }
                            }}
                            disabled={isMerging}
                            className="shrink-0 ml-3 inline-flex items-center gap-1 px-3 py-1.5 text-xs font-medium text-blue-600 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 disabled:opacity-50 transition-colors"
                          >
                            {ci === 0 ? (
                              <>
                                <GitMerge className="w-3.5 h-3.5" />
                                これに統合
                              </>
                            ) : (
                              <>
                                <GitMerge className="w-3.5 h-3.5" />
                                これに統合
                              </>
                            )}
                          </button>
                        </div>
                      ))}
                    </div>
                  </div>
                ))
              )}
            </div>

            {/* モーダルフッター */}
            <div className="px-5 py-3 border-t border-slate-200 bg-slate-50 rounded-b-lg">
              <p className="text-[10px] text-slate-400">
                「これに統合」をクリックすると、選択したコンタクトに他の重複コンタクトのチャネル・イベント・プロジェクトが移行され、重複分は削除されます。
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
