// Phase UI-7: 組織詳細ページ（左ツリーナビ + 右コンテンツ統合）
'use client';

import { useState, useEffect, useCallback } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  Building2, ArrowLeft, Globe, Save, Hash, Mail, MessageSquare,
  Users, UserPlus, Trash2, Search, Wand2, X, Plus, Link2, FolderOpen,
  ChevronRight, ChevronDown, Settings, CheckSquare, Clock, FileText,
  ClipboardList, GitBranch, Map, Briefcase, Edit3,
} from 'lucide-react';
import AppLayout from '@/components/shared/AppLayout';
import ContextBar from '@/components/shared/ContextBar';
import MoreMenu from '@/components/shared/MoreMenu';
import DeleteConfirmDialog from '@/components/shared/DeleteConfirmDialog';
import BusinessTimeline from '@/components/organizations/BusinessTimeline';
import { PROJECT_STATUS_LABELS } from '@/components/business-log/types';

// ========================================
// 型定義
// ========================================
interface Organization {
  id: string;
  name: string;
  domain: string | null;
  relationship_type: string | null;
  address: string | null;
  phone: string | null;
  memo: string | null;
  created_at: string;
  updated_at: string;
}

interface OrgChannel {
  id: string;
  organization_id: string;
  service_name: 'slack' | 'chatwork' | 'email';
  channel_id: string;
  channel_name: string;
  channel_type: string | null;
  is_active: boolean;
  created_at: string;
}

interface Member {
  id: string;
  name: string;
  relationship_type: string | null;
  main_channel: string | null;
  message_count: number | null;
  last_contact_at: string | null;
  is_team_member: boolean | null;
  auto_added_to_org: boolean | null;
  confirmed: boolean | null;
  linked_user_id: string | null;
}

interface NodeMapUser {
  id: string;
  email: string;
  displayName: string;
}

interface AvailableChannel {
  channel_id: string;
  channel_name: string;
  channel_type: string;
  member_count?: number;
  is_subscribed: boolean;
}

interface Contact {
  id: string;
  name: string;
  companyName?: string;
  organization_id?: string;
  address?: string;
  mainChannel?: string;
  messageCount?: number;
  lastContactAt?: string;
  isAutoGenerated?: boolean;
}

interface Project {
  id: string;
  name: string;
  description: string | null;
  status: string;
  organization_id?: string | null;
  created_at: string;
  updated_at: string;
}

interface Task {
  id: string;
  title: string;
  status: string;
  priority: string;
  due_date: string | null;
}

// ========================================
// ツリーナビのノードタイプ
// ========================================
type NavNode =
  | { type: 'org'; tab: 'members' | 'channels' | 'settings' }
  | { type: 'project'; projectId: string; tab: 'timeline' | 'decision-tree' | 'thought-map' | 'tasks' | 'jobs' };

// ========================================
// サービスアイコン
// ========================================
function ServiceIcon({ service }: { service: string }) {
  switch (service) {
    case 'slack': return <Hash className="w-4 h-4 text-purple-600" />;
    case 'chatwork': return <MessageSquare className="w-4 h-4 text-green-600" />;
    case 'email': return <Mail className="w-4 h-4 text-blue-600" />;
    default: return <Link2 className="w-4 h-4 text-slate-400" />;
  }
}

function ServiceBadge({ service }: { service: string }) {
  const config: Record<string, { label: string; bg: string; text: string }> = {
    slack: { label: 'Slack', bg: 'bg-purple-50', text: 'text-purple-700' },
    chatwork: { label: 'Chatwork', bg: 'bg-green-50', text: 'text-green-700' },
    email: { label: 'Email', bg: 'bg-blue-50', text: 'text-blue-700' },
  };
  const c = config[service] || { label: service, bg: 'bg-slate-50', text: 'text-slate-700' };
  return (
    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium ${c.bg} ${c.text}`}>
      <ServiceIcon service={service} />
      {c.label}
    </span>
  );
}

// ========================================
// メインコンポーネント
// ========================================
export default function OrganizationDetailPage() {
  const params = useParams();
  const router = useRouter();
  const orgId = params.id as string;

  // ナビゲーション
  const [activeNav, setActiveNav] = useState<NavNode>({ type: 'org', tab: 'members' });
  const [expandedProjects, setExpandedProjects] = useState<Set<string>>(new Set());

  // 組織情報
  const [org, setOrg] = useState<Organization | null>(null);
  const [editName, setEditName] = useState('');
  const [editDomain, setEditDomain] = useState('');
  const [editRelType, setEditRelType] = useState('');
  const [editAddress, setEditAddress] = useState('');
  const [editPhone, setEditPhone] = useState('');
  const [editMemo, setEditMemo] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  // プロジェクト
  const [projects, setProjects] = useState<Project[]>([]);
  const [showNewProject, setShowNewProject] = useState(false);
  const [newProjectName, setNewProjectName] = useState('');
  const [newProjectDesc, setNewProjectDesc] = useState('');

  // チャネル
  const [channels, setChannels] = useState<OrgChannel[]>([]);
  const [showChannelForm, setShowChannelForm] = useState(false);
  const [channelService, setChannelService] = useState<'slack' | 'chatwork' | 'email'>('slack');
  const [availableChannels, setAvailableChannels] = useState<AvailableChannel[]>([]);
  const [channelSearch, setChannelSearch] = useState('');
  const [loadingChannels, setLoadingChannels] = useState(false);
  const [emailDomain, setEmailDomain] = useState('');

  // メンバー
  const [members, setMembers] = useState<Member[]>([]);
  const [showMemberForm, setShowMemberForm] = useState(false);
  const [allContacts, setAllContacts] = useState<Contact[]>([]);
  const [memberSearch, setMemberSearch] = useState('');
  const [detecting, setDetecting] = useState(false);
  const [nodeMapUsers, setNodeMapUsers] = useState<NodeMapUser[]>([]);

  // タスク（PJ選択時）
  const [tasks, setTasks] = useState<Task[]>([]);
  const [isLoadingTasks, setIsLoadingTasks] = useState(false);

  // ドキュメント（PJ選択時）
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [documents, setDocuments] = useState<any[]>([]);
  const [isLoadingDocs, setIsLoadingDocs] = useState(false);

  // 削除ダイアログ
  const [deleteDialog, setDeleteDialog] = useState<{
    type: 'project' | 'task';
    id: string;
    name: string;
  } | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  // メッセージ
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  const showMsg = (type: 'success' | 'error', text: string) => {
    setMessage({ type, text });
    setTimeout(() => setMessage(null), 4000);
  };

  // ========================================
  // 削除処理
  // ========================================
  const handleDeleteConfirm = async () => {
    if (!deleteDialog) return;
    setIsDeleting(true);
    try {
      let url = '';
      let method = 'DELETE';
      if (deleteDialog.type === 'project') {
        url = `/api/projects/${deleteDialog.id}`;
      } else if (deleteDialog.type === 'task') {
        url = `/api/tasks?id=${deleteDialog.id}`;
      }
      const res = await fetch(url, { method });
      if (res.ok) {
        showMsg('success', `${deleteDialog.name} を削除しました`);
        if (deleteDialog.type === 'project') {
          setProjects(prev => prev.filter(p => p.id !== deleteDialog.id));
          setActiveNav({ type: 'org', tab: 'members' });
        } else if (deleteDialog.type === 'task') {
          setTasks(prev => prev.filter(t => t.id !== deleteDialog.id));
        }
      } else {
        showMsg('error', '削除に失敗しました');
      }
    } catch {
      showMsg('error', '削除に失敗しました');
    } finally {
      setIsDeleting(false);
      setDeleteDialog(null);
    }
  };

  // ========================================
  // データ取得
  // ========================================
  const fetchOrg = useCallback(async () => {
    try {
      const res = await fetch('/api/organizations');
      const data = await res.json();
      if (data.success) {
        const found = (data.data || []).find((o: Organization) => o.id === orgId);
        if (found) {
          setOrg(found);
          setEditName(found.name);
          setEditDomain(found.domain || '');
          setEditRelType(found.relationship_type || '');
          setEditAddress(found.address || '');
          setEditPhone(found.phone || '');
          setEditMemo(found.memo || '');
        }
      }
    } catch { /* */ }
  }, [orgId]);

  const fetchChannels = useCallback(async () => {
    try {
      const res = await fetch(`/api/organizations/${orgId}/channels`);
      const data = await res.json();
      if (data.success) setChannels(data.data || []);
    } catch { /* */ }
  }, [orgId]);

  const fetchMembers = useCallback(async () => {
    try {
      const res = await fetch(`/api/organizations/${orgId}/members`);
      const data = await res.json();
      if (data.success) setMembers(data.data || []);
    } catch { /* */ }
  }, [orgId]);

  const fetchProjects = useCallback(async () => {
    try {
      const res = await fetch(`/api/projects?organization_id=${orgId}`);
      const data = await res.json();
      if (data.success) setProjects(data.data || []);
    } catch { /* */ }
  }, [orgId]);

  const fetchNodeMapUsers = useCallback(async () => {
    try {
      const res = await fetch('/api/users');
      const data = await res.json();
      if (data.success) setNodeMapUsers(data.data || []);
    } catch { /* */ }
  }, []);

  useEffect(() => {
    const load = async () => {
      setIsLoading(true);
      await Promise.all([fetchOrg(), fetchChannels(), fetchMembers(), fetchProjects(), fetchNodeMapUsers()]);
      setIsLoading(false);
    };
    load();
  }, [fetchOrg, fetchChannels, fetchMembers, fetchProjects, fetchNodeMapUsers]);

  // PJタスク取得
  const fetchTasks = useCallback(async (projectId: string) => {
    setIsLoadingTasks(true);
    try {
      const res = await fetch(`/api/tasks?project_id=${projectId}`);
      const data = await res.json();
      if (data.success) setTasks(data.data || []);
    } catch { /* */ }
    finally { setIsLoadingTasks(false); }
  }, []);

  // PJドキュメント取得
  const fetchDocuments = useCallback(async (projectId: string) => {
    setIsLoadingDocs(true);
    try {
      const res = await fetch(`/api/drive/documents?projectId=${projectId}`);
      const data = await res.json();
      if (data.success) setDocuments(data.data || []);
    } catch { /* */ }
    finally { setIsLoadingDocs(false); }
  }, []);

  // ナビ変更時のデータロード
  useEffect(() => {
    if (activeNav.type === 'project') {
      if (activeNav.tab === 'tasks') fetchTasks(activeNav.projectId);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeNav]);

  // ========================================
  // 組織情報の保存
  // ========================================
  const saveOrg = async () => {
    if (!editName.trim()) return;
    try {
      const res = await fetch(`/api/organizations/${orgId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: editName.trim(),
          domain: editDomain.trim() || null,
          relationship_type: editRelType || null,
          address: editAddress.trim() || null,
          phone: editPhone.trim() || null,
          memo: editMemo.trim() || null,
        }),
      });
      const data = await res.json();
      if (data.success) {
        setOrg(data.data);
        showMsg('success', '組織情報を更新しました');
        if (editRelType) fetchMembers();
      } else {
        showMsg('error', data.error || '更新に失敗しました');
      }
    } catch { showMsg('error', '通信エラー'); }
  };

  // ========================================
  // チャネル操作
  // ========================================
  const fetchAvailableChannels = async (service: string) => {
    setLoadingChannels(true);
    try {
      const res = await fetch(`/api/settings/channels/available?service=${service}`);
      const data = await res.json();
      if (data.success) {
        const linkedIds = new Set(channels.filter(c => c.service_name === service).map(c => c.channel_id));
        setAvailableChannels((data.data || []).filter((ch: AvailableChannel) => !linkedIds.has(ch.channel_id)));
      }
    } catch { /* */ }
    setLoadingChannels(false);
  };

  const addChannel = async (channelId: string, channelName: string, channelType: string) => {
    try {
      const res = await fetch(`/api/organizations/${orgId}/channels`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ service_name: channelService, channel_id: channelId, channel_name: channelName, channel_type: channelType }),
      });
      const data = await res.json();
      if (data.success) {
        showMsg('success', `${channelName} を追加しました`);
        fetchChannels();
        setAvailableChannels(prev => prev.filter(c => c.channel_id !== channelId));
      } else { showMsg('error', data.error || '追加に失敗しました'); }
    } catch { showMsg('error', '通信エラー'); }
  };

  const addEmailDomain = async () => {
    const domain = emailDomain.trim().replace(/^@/, '');
    if (!domain) return;
    await addChannel(`@${domain}`, `@${domain}`, 'domain');
    setEmailDomain('');
  };

  const removeChannel = async (channelDbId: string) => {
    if (!confirm('このチャネルの紐づけを解除しますか？')) return;
    try {
      const res = await fetch(`/api/organizations/${orgId}/channels?channelId=${channelDbId}`, { method: 'DELETE' });
      const data = await res.json();
      if (data.success) { showMsg('success', 'チャネルを解除しました'); fetchChannels(); }
    } catch { showMsg('error', '通信エラー'); }
  };

  // ========================================
  // メンバー操作
  // ========================================
  const fetchAllContacts = async () => {
    try {
      const res = await fetch('/api/contacts');
      const data = await res.json();
      if (data.success) {
        const memberIds = new Set(members.map(m => m.id));
        const mapped = (data.data || [])
          .filter((c: Record<string, unknown>) => !memberIds.has(c.id as string))
          .map((c: Record<string, unknown>) => ({
            id: c.id as string, name: c.name as string,
            companyName: c.companyName as string | undefined,
            organization_id: c.organization_id as string | undefined,
            address: c.address as string | undefined,
            mainChannel: c.mainChannel as string | undefined,
            messageCount: c.messageCount as number | undefined,
            lastContactAt: c.lastContactAt as string | undefined,
            isAutoGenerated: c.isAutoGenerated as boolean | undefined,
          }));
        setAllContacts(mapped);
      }
    } catch { /* */ }
  };

  const addMember = async (contactId: string) => {
    try {
      const contact = allContacts.find(c => c.id === contactId);
      const isAuto = contactId.startsWith('auto_') || contact?.isAutoGenerated;
      const bodyPayload = isAuto && contact
        ? { auto_contacts: [{ name: contact.name, address: contact.address || '', channel: contact.mainChannel || 'email', messageCount: contact.messageCount || 0, lastContactAt: contact.lastContactAt || null }] }
        : { contact_ids: [contactId] };
      const res = await fetch(`/api/organizations/${orgId}/members`, {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(bodyPayload),
      });
      const data = await res.json();
      if (data.success) {
        showMsg('success', 'メンバーを追加しました');
        fetchMembers();
        setAllContacts(prev => prev.filter(c => c.id !== contactId));
      } else { showMsg('error', data.error || 'メンバー追加に失敗しました'); }
    } catch { showMsg('error', '通信エラー'); }
  };

  const removeMember = async (contactId: string) => {
    if (!confirm('このメンバーを組織から外しますか？')) return;
    try {
      const res = await fetch(`/api/organizations/${orgId}/members?contactId=${contactId}`, { method: 'DELETE' });
      const data = await res.json();
      if (data.success) { showMsg('success', 'メンバーを外しました'); fetchMembers(); }
    } catch { showMsg('error', '通信エラー'); }
  };

  const linkMemberUser = async (contactId: string, linkedUserId: string) => {
    try {
      const res = await fetch(`/api/organizations/${orgId}/members`, {
        method: 'PATCH', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ contactId, linkedUserId: linkedUserId || null }),
      });
      const data = await res.json();
      if (data.success) {
        setMembers(prev => prev.map(m => m.id === contactId ? { ...m, linked_user_id: linkedUserId || null } : m));
        showMsg('success', linkedUserId ? 'アカウントを紐づけました' : '紐づけを解除しました');
      } else { showMsg('error', data.error || '紐づけに失敗しました'); }
    } catch { showMsg('error', '通信エラー'); }
  };

  const detectMembers = async () => {
    setDetecting(true);
    try {
      const res = await fetch(`/api/organizations/${orgId}/detect-members`, { method: 'POST' });
      const data = await res.json();
      if (data.success) {
        showMsg('success', data.message || `${data.data?.added || 0}人追加`);
        if (data.data?.added > 0) fetchMembers();
      } else { showMsg('error', data.error || '検出に失敗しました'); }
    } catch { showMsg('error', '通信エラー'); }
    setDetecting(false);
  };

  // ========================================
  // プロジェクト作成
  // ========================================
  const createProject = async () => {
    if (!newProjectName.trim()) return;
    try {
      const res = await fetch('/api/projects', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: newProjectName.trim(), description: newProjectDesc.trim() || null, organizationId: orgId }),
      });
      const data = await res.json();
      if (data.success) {
        setShowNewProject(false); setNewProjectName(''); setNewProjectDesc('');
        fetchProjects();
        showMsg('success', 'プロジェクトを作成しました');
      } else { showMsg('error', data.error || '作成に失敗しました'); }
    } catch { showMsg('error', '通信エラー'); }
  };

  // チャネルフォーム
  useEffect(() => {
    if (showChannelForm && channelService !== 'email') fetchAvailableChannels(channelService);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showChannelForm, channelService]);

  useEffect(() => {
    if (showMemberForm) fetchAllContacts();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showMemberForm]);

  const filteredAvailableChannels = availableChannels.filter(ch =>
    ch.channel_name.toLowerCase().includes(channelSearch.toLowerCase())
  );

  const filteredContacts = allContacts.filter(c =>
    c.name.toLowerCase().includes(memberSearch.toLowerCase())
  );

  // ツリーナビのPJトグル
  const toggleProject = (projectId: string) => {
    setExpandedProjects(prev => {
      const next = new Set(prev);
      if (next.has(projectId)) next.delete(projectId);
      else next.add(projectId);
      return next;
    });
  };

  // ========================================
  // レンダリング
  // ========================================
  if (isLoading) {
    return (
      <AppLayout>
        <ContextBar title="組織詳細" />
        <div className="flex-1 flex items-center justify-center text-slate-400">
          <div className="text-center">
            <div className="animate-spin text-2xl mb-2">&#8987;</div>
            <p className="text-sm">読み込み中...</p>
          </div>
        </div>
      </AppLayout>
    );
  }

  if (!org) {
    return (
      <AppLayout>
        <ContextBar title="組織詳細" />
        <div className="flex-1 flex items-center justify-center text-slate-400">
          <div className="text-center">
            <Building2 className="w-12 h-12 mx-auto mb-3 text-slate-300" />
            <p className="text-sm">組織が見つかりません</p>
            <button onClick={() => router.push('/organizations')} className="mt-3 text-xs text-blue-600 hover:underline">一覧に戻る</button>
          </div>
        </div>
      </AppLayout>
    );
  }

  // 現在のPJ（PJタブ選択時）
  const currentProject = activeNav.type === 'project'
    ? projects.find(p => p.id === activeNav.projectId)
    : null;

  return (
    <AppLayout>
      <ContextBar title="組織詳細" />
      <div className="flex-1 overflow-hidden flex flex-col">
        {/* ヘッダー */}
        <div className="px-6 py-3 border-b border-slate-200 bg-slate-50 shrink-0">
          <div className="flex items-center gap-3">
            <button onClick={() => router.push('/organizations')} className="p-1.5 rounded-lg hover:bg-slate-200 transition-colors">
              <ArrowLeft className="w-4 h-4 text-slate-600" />
            </button>
            <div className="w-9 h-9 rounded-lg bg-blue-50 flex items-center justify-center">
              <Building2 className="w-5 h-5 text-blue-600" />
            </div>
            <div className="flex-1 min-w-0">
              <h1 className="text-base font-bold text-slate-900 truncate">{org.name}</h1>
              {org.domain && (
                <p className="text-[11px] text-slate-500 flex items-center gap-1">
                  <Globe className="w-3 h-3" />{org.domain}
                </p>
              )}
            </div>
            <div className="flex items-center gap-3 text-xs text-slate-500">
              <span className="flex items-center gap-1"><FolderOpen className="w-3.5 h-3.5" />{projects.length} PJ</span>
              <span className="flex items-center gap-1"><Users className="w-3.5 h-3.5" />{members.length}人</span>
              <span className="flex items-center gap-1"><Link2 className="w-3.5 h-3.5" />{channels.length} ch</span>
            </div>
          </div>
        </div>

        {/* メッセージバナー */}
        {message && (
          <div className={`mx-6 mt-2 px-3 py-2 rounded-lg text-xs font-medium shrink-0 ${
            message.type === 'success' ? 'bg-green-50 text-green-700 border border-green-200' : 'bg-red-50 text-red-700 border border-red-200'
          }`}>{message.text}</div>
        )}

        {/* 2カラムレイアウト: 左ツリーナビ + 右コンテンツ */}
        <div className="flex-1 overflow-hidden flex">
          {/* ===== 左ツリーナビ ===== */}
          <div className="w-56 shrink-0 border-r border-slate-200 bg-white overflow-y-auto">
            <div className="py-2">
              {/* 組織レベルメニュー */}
              <div className="px-3 mb-1">
                <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider px-2 py-1">組織</p>
              </div>
              {[
                { tab: 'members' as const, label: 'メンバー', icon: Users, count: members.length },
                { tab: 'channels' as const, label: 'チャネル', icon: Link2, count: channels.length },
                { tab: 'settings' as const, label: '設定', icon: Settings, count: 0 },
              ].map(item => (
                <button
                  key={item.tab}
                  onClick={() => setActiveNav({ type: 'org', tab: item.tab })}
                  className={`w-full flex items-center gap-2 px-5 py-2 text-xs transition-colors ${
                    activeNav.type === 'org' && activeNav.tab === item.tab
                      ? 'bg-blue-50 text-blue-700 font-medium'
                      : 'text-slate-600 hover:bg-slate-50'
                  }`}
                >
                  <item.icon className="w-3.5 h-3.5" />
                  <span className="flex-1 text-left">{item.label}</span>
                  {item.count > 0 && (
                    <span className="text-[10px] px-1.5 py-0.5 bg-slate-100 rounded-full">{item.count}</span>
                  )}
                </button>
              ))}

              {/* プロジェクト一覧 */}
              <div className="px-3 mt-4 mb-1 flex items-center justify-between">
                <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider px-2 py-1">プロジェクト</p>
                <button
                  onClick={() => setShowNewProject(true)}
                  className="p-1 rounded hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-colors"
                  title="新規プロジェクト"
                >
                  <Plus className="w-3.5 h-3.5" />
                </button>
              </div>

              {projects.length === 0 ? (
                <p className="px-5 py-2 text-[11px] text-slate-400">プロジェクトなし</p>
              ) : (
                projects.map(project => {
                  const isExpanded = expandedProjects.has(project.id);
                  const statusConfig = PROJECT_STATUS_LABELS[project.status] || PROJECT_STATUS_LABELS.active;
                  return (
                    <div key={project.id}>
                      <div className="flex items-center hover:bg-slate-50 transition-colors">
                        <button
                          onClick={() => toggleProject(project.id)}
                          className="flex-1 flex items-center gap-1.5 px-5 py-2 text-xs text-slate-700"
                        >
                          {isExpanded ? (
                            <ChevronDown className="w-3 h-3 text-slate-400 shrink-0" />
                          ) : (
                            <ChevronRight className="w-3 h-3 text-slate-400 shrink-0" />
                          )}
                          <FolderOpen className="w-3.5 h-3.5 text-blue-500 shrink-0" />
                          <span className="flex-1 text-left truncate">{project.name}</span>
                          <span className={`text-[9px] px-1 py-0.5 rounded-full shrink-0 ${statusConfig.color}`}>
                            {statusConfig.label}
                          </span>
                        </button>
                        <div className="pr-2">
                          <MoreMenu items={[
                            { label: '削除', icon: <Trash2 className="w-3 h-3" />, onClick: () => setDeleteDialog({ type: 'project', id: project.id, name: project.name }), variant: 'danger' },
                          ]} />
                        </div>
                      </div>
                      {isExpanded && (
                        <div className="ml-4">
                          {[
                            { tab: 'timeline' as const, label: 'タイムライン', icon: Clock },
                            { tab: 'decision-tree' as const, label: '検討ツリー', icon: GitBranch },
                            { tab: 'thought-map' as const, label: '思考マップ', icon: Map },
                            { tab: 'tasks' as const, label: 'タスク', icon: CheckSquare },
                            { tab: 'jobs' as const, label: 'ジョブ', icon: Briefcase },
                          ].map(sub => (
                            <button
                              key={sub.tab}
                              onClick={() => setActiveNav({ type: 'project', projectId: project.id, tab: sub.tab })}
                              className={`w-full flex items-center gap-2 px-5 py-1.5 text-[11px] transition-colors ${
                                activeNav.type === 'project' && activeNav.projectId === project.id && activeNav.tab === sub.tab
                                  ? 'bg-blue-50 text-blue-700 font-medium'
                                  : 'text-slate-500 hover:bg-slate-50'
                              }`}
                            >
                              <sub.icon className="w-3 h-3" />
                              {sub.label}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })
              )}

              {/* 新規PJ作成フォーム */}
              {showNewProject && (
                <div className="mx-3 mt-2 p-2 bg-slate-50 border border-slate-200 rounded-lg">
                  <input
                    type="text" value={newProjectName} onChange={(e) => setNewProjectName(e.target.value)}
                    placeholder="プロジェクト名" autoFocus
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-blue-500 mb-1.5"
                  />
                  <textarea
                    value={newProjectDesc} onChange={(e) => setNewProjectDesc(e.target.value)}
                    placeholder="説明（任意）" rows={2}
                    className="w-full px-2 py-1.5 text-xs border border-slate-200 rounded focus:outline-none focus:ring-1 focus:ring-blue-500 resize-none mb-1.5"
                  />
                  <div className="flex gap-1.5">
                    <button onClick={createProject} disabled={!newProjectName.trim()}
                      className="px-2.5 py-1 text-[10px] font-medium text-white bg-blue-600 rounded hover:bg-blue-700 disabled:opacity-50 transition-colors">
                      作成
                    </button>
                    <button onClick={() => { setShowNewProject(false); setNewProjectName(''); setNewProjectDesc(''); }}
                      className="px-2.5 py-1 text-[10px] font-medium text-slate-600 bg-white border border-slate-200 rounded hover:bg-slate-50 transition-colors">
                      取消
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* ===== 右コンテンツエリア ===== */}
          <div className="flex-1 overflow-hidden flex flex-col">
            <div className="flex-1 overflow-y-auto">
              {/* 組織レベル: メンバー */}
              {activeNav.type === 'org' && activeNav.tab === 'members' && (
                <div className="p-6 space-y-4">
                  <div className="flex items-center justify-between">
                    <h2 className="text-sm font-bold text-slate-800">メンバー</h2>
                    <div className="flex gap-2">
                      <button onClick={detectMembers} disabled={detecting || channels.length === 0}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-amber-700 bg-amber-50 border border-amber-200 rounded-lg hover:bg-amber-100 disabled:opacity-50 transition-colors"
                        title={channels.length === 0 ? '先にチャネルを紐づけてください' : '自動検出'}>
                        <Wand2 className="w-3.5 h-3.5" />{detecting ? '検出中...' : '自動検出'}
                      </button>
                      <button onClick={() => { setShowMemberForm(!showMemberForm); setMemberSearch(''); }}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors">
                        <UserPlus className="w-3.5 h-3.5" />追加
                      </button>
                    </div>
                  </div>

                  {showMemberForm && (
                    <div className="p-4 bg-slate-50 border border-slate-200 rounded-lg">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-sm font-semibold text-slate-700">コンタクトから追加</h3>
                        <button onClick={() => setShowMemberForm(false)} className="text-slate-400 hover:text-slate-600"><X className="w-4 h-4" /></button>
                      </div>
                      <div className="relative mb-3">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                        <input type="text" value={memberSearch} onChange={(e) => setMemberSearch(e.target.value)} placeholder="コンタクトを検索..."
                          className="w-full pl-9 pr-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
                      </div>
                      <div className="max-h-60 overflow-y-auto space-y-1">
                        {filteredContacts.length === 0 ? (
                          <p className="text-xs text-slate-400 text-center py-4">該当するコンタクトがありません</p>
                        ) : filteredContacts.slice(0, 50).map(c => (
                          <div key={c.id} className="flex items-center justify-between p-2 rounded-lg hover:bg-white transition-colors">
                            <div>
                              <span className="text-sm text-slate-700">{c.name}</span>
                              {c.companyName && <span className="ml-2 text-[10px] text-slate-400">{c.companyName}</span>}
                            </div>
                            <button onClick={() => addMember(c.id)}
                              className="px-2 py-1 text-[10px] font-medium text-blue-600 bg-blue-50 rounded hover:bg-blue-100 transition-colors">追加</button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {members.length === 0 ? (
                    <div className="flex items-center justify-center h-32 text-slate-400">
                      <div className="text-center">
                        <Users className="w-8 h-8 mx-auto mb-2 text-slate-300" />
                        <p className="text-xs">メンバーがいません</p>
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {members.map(m => (
                        <div key={m.id} className="p-3 bg-white border border-slate-200 rounded-lg">
                          <div className="flex items-center justify-between">
                            <div className="flex items-center gap-3">
                              <div className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center text-xs font-bold text-slate-500">
                                {m.name.charAt(0)}
                              </div>
                              <div>
                                <div className="flex items-center gap-2">
                                  <span className="text-sm font-medium text-slate-700">{m.name}</span>
                                  {m.auto_added_to_org && (
                                    <span className="px-1.5 py-0.5 text-[10px] font-medium bg-amber-50 text-amber-600 border border-amber-200 rounded-full">自動追加</span>
                                  )}
                                </div>
                                <div className="flex items-center gap-3 mt-0.5">
                                  {m.main_channel && <span className="text-[10px] text-slate-400">{m.main_channel}</span>}
                                  {m.message_count != null && m.message_count > 0 && <span className="text-[10px] text-slate-400">{m.message_count}件</span>}
                                  {m.last_contact_at && <span className="text-[10px] text-slate-400">最終: {new Date(m.last_contact_at).toLocaleDateString('ja-JP')}</span>}
                                </div>
                              </div>
                            </div>
                            <button onClick={() => removeMember(m.id)}
                              className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors" title="外す">
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                          {org?.relationship_type === 'internal' && nodeMapUsers.length > 0 && (
                            <div className="mt-2 pt-2 border-t border-slate-100 flex items-center gap-2">
                              <span className="text-[10px] text-slate-400 whitespace-nowrap">NodeMapアカウント:</span>
                              <select value={m.linked_user_id || ''} onChange={(e) => linkMemberUser(m.id, e.target.value)}
                                className="flex-1 border border-slate-200 rounded px-2 py-1 text-[11px] focus:outline-none focus:ring-1 focus:ring-blue-500">
                                <option value="">未紐づけ</option>
                                {nodeMapUsers.map(u => <option key={u.id} value={u.id}>{u.displayName} ({u.email})</option>)}
                              </select>
                              {m.linked_user_id && <span className="text-[10px] text-green-600">&#10003;</span>}
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* 組織レベル: チャネル */}
              {activeNav.type === 'org' && activeNav.tab === 'channels' && (
                <div className="p-6 space-y-4">
                  <div className="flex items-center justify-between">
                    <h2 className="text-sm font-bold text-slate-800">チャネル</h2>
                    <button onClick={() => { setShowChannelForm(!showChannelForm); setChannelSearch(''); }}
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors">
                      <Plus className="w-3.5 h-3.5" />追加
                    </button>
                  </div>

                  {showChannelForm && (
                    <div className="p-4 bg-slate-50 border border-slate-200 rounded-lg">
                      <div className="flex items-center justify-between mb-3">
                        <h3 className="text-sm font-semibold text-slate-700">チャネルを追加</h3>
                        <button onClick={() => setShowChannelForm(false)} className="text-slate-400 hover:text-slate-600"><X className="w-4 h-4" /></button>
                      </div>
                      <div className="flex gap-2 mb-3">
                        {(['slack', 'chatwork', 'email'] as const).map(svc => (
                          <button key={svc} onClick={() => { setChannelService(svc); setChannelSearch(''); }}
                            className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-lg transition-colors ${
                              channelService === svc ? 'bg-blue-600 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-100'
                            }`}>
                            <ServiceIcon service={svc} />{svc === 'slack' ? 'Slack' : svc === 'chatwork' ? 'Chatwork' : 'Email'}
                          </button>
                        ))}
                      </div>
                      {channelService === 'email' ? (
                        <div className="flex gap-2">
                          <input type="text" value={emailDomain} onChange={(e) => setEmailDomain(e.target.value)} placeholder="例: example.co.jp"
                            className="flex-1 px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
                          <button onClick={addEmailDomain} disabled={!emailDomain.trim()}
                            className="px-4 py-2 text-xs font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors">追加</button>
                        </div>
                      ) : (
                        <>
                          <div className="relative mb-3">
                            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                            <input type="text" value={channelSearch} onChange={(e) => setChannelSearch(e.target.value)} placeholder="チャネルを検索..."
                              className="w-full pl-9 pr-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
                          </div>
                          <div className="max-h-60 overflow-y-auto space-y-1">
                            {loadingChannels ? (
                              <p className="text-xs text-slate-400 text-center py-4">読み込み中...</p>
                            ) : filteredAvailableChannels.length === 0 ? (
                              <p className="text-xs text-slate-400 text-center py-4">利用可能なチャネルがありません</p>
                            ) : filteredAvailableChannels.map(ch => (
                              <div key={ch.channel_id} className="flex items-center justify-between p-2 rounded-lg hover:bg-white transition-colors">
                                <div className="flex items-center gap-2">
                                  <ServiceIcon service={channelService} />
                                  <span className="text-sm text-slate-700">{ch.channel_name}</span>
                                  {ch.member_count !== undefined && <span className="text-[10px] text-slate-400">{ch.member_count}人</span>}
                                </div>
                                <button onClick={() => addChannel(ch.channel_id, ch.channel_name, ch.channel_type)}
                                  className="px-2 py-1 text-[10px] font-medium text-blue-600 bg-blue-50 rounded hover:bg-blue-100 transition-colors">追加</button>
                              </div>
                            ))}
                          </div>
                        </>
                      )}
                    </div>
                  )}

                  {channels.length === 0 ? (
                    <div className="flex items-center justify-center h-32 text-slate-400">
                      <div className="text-center">
                        <Link2 className="w-8 h-8 mx-auto mb-2 text-slate-300" />
                        <p className="text-xs">チャネルが紐づけられていません</p>
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {channels.map(ch => (
                        <div key={ch.id} className="flex items-center justify-between p-3 bg-white border border-slate-200 rounded-lg">
                          <div className="flex items-center gap-3">
                            <ServiceBadge service={ch.service_name} />
                            <span className="text-sm font-medium text-slate-700">{ch.channel_name}</span>
                            {ch.channel_type && <span className="text-[10px] text-slate-400">{ch.channel_type}</span>}
                          </div>
                          <button onClick={() => removeChannel(ch.id)}
                            className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors" title="解除">
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* 組織レベル: 設定 */}
              {activeNav.type === 'org' && activeNav.tab === 'settings' && (
                <div className="p-6">
                  <h2 className="text-sm font-bold text-slate-800 mb-4">組織設定</h2>
                  <div className="max-w-lg space-y-4">
                    <div>
                      <label className="flex items-center gap-1.5 text-xs font-medium text-slate-600 mb-1"><Building2 className="w-3.5 h-3.5" />組織名</label>
                      <input type="text" value={editName} onChange={(e) => setEditName(e.target.value)}
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
                    </div>
                    <div>
                      <label className="flex items-center gap-1.5 text-xs font-medium text-slate-600 mb-1"><Users className="w-3.5 h-3.5" />関係性</label>
                      <select value={editRelType} onChange={(e) => setEditRelType(e.target.value)}
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white">
                        <option value="">未設定</option>
                        <option value="internal">自社</option>
                        <option value="client">取引先</option>
                        <option value="partner">パートナー</option>
                        <option value="vendor">仕入先</option>
                        <option value="prospect">見込み</option>
                      </select>
                    </div>
                    <div>
                      <label className="flex items-center gap-1.5 text-xs font-medium text-slate-600 mb-1"><Globe className="w-3.5 h-3.5" />ドメイン</label>
                      <input type="text" value={editDomain} onChange={(e) => setEditDomain(e.target.value)} placeholder="例: example.co.jp"
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
                    </div>
                    <div>
                      <label className="text-xs font-medium text-slate-600 mb-1 block">住所</label>
                      <input type="text" value={editAddress} onChange={(e) => setEditAddress(e.target.value)} placeholder="例: 東京都渋谷区..."
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
                    </div>
                    <div>
                      <label className="text-xs font-medium text-slate-600 mb-1 block">電話番号</label>
                      <input type="text" value={editPhone} onChange={(e) => setEditPhone(e.target.value)} placeholder="例: 03-1234-5678"
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
                    </div>
                    <div>
                      <label className="text-xs font-medium text-slate-600 mb-1 block">メモ</label>
                      <textarea value={editMemo} onChange={(e) => setEditMemo(e.target.value)} placeholder="備考・メモ" rows={3}
                        className="w-full px-3 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none" />
                    </div>
                    <button onClick={saveOrg} disabled={!editName.trim()}
                      className="inline-flex items-center gap-1.5 px-4 py-2 text-xs font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors">
                      <Save className="w-3.5 h-3.5" />保存
                    </button>
                  </div>
                </div>
              )}

              {/* PJレベル: タイムライン */}
              {activeNav.type === 'project' && activeNav.tab === 'timeline' && currentProject && (
                <BusinessTimeline projectId={currentProject.id} projectName={currentProject.name} />
              )}

              {/* PJレベル: タスク */}
              {activeNav.type === 'project' && activeNav.tab === 'tasks' && (
                <div className="p-6">
                  <div className="flex items-center justify-between mb-4">
                    <h2 className="text-sm font-bold text-slate-800">{currentProject?.name} - タスク</h2>
                    <a href={`/tasks?project_id=${activeNav.projectId}`} className="text-xs text-blue-600 hover:underline">タスクページで管理</a>
                  </div>
                  {isLoadingTasks ? (
                    <div className="flex items-center justify-center py-16"><div className="animate-spin text-2xl">&#8987;</div></div>
                  ) : tasks.length === 0 ? (
                    <div className="flex items-center justify-center h-32 text-slate-400">
                      <div className="text-center">
                        <CheckSquare className="w-8 h-8 mx-auto mb-2 text-slate-300" />
                        <p className="text-xs">タスクがありません</p>
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      {(['in_progress', 'todo', 'done'] as const).map(status => {
                        const statusTasks = tasks.filter(t => t.status === status);
                        if (statusTasks.length === 0) return null;
                        const statusLabels: Record<string, string> = { todo: '未着手', in_progress: '進行中', done: '完了' };
                        const statusColors: Record<string, string> = { todo: 'bg-slate-100 text-slate-600', in_progress: 'bg-blue-100 text-blue-700', done: 'bg-green-100 text-green-700' };
                        return (
                          <div key={status}>
                            <div className="flex items-center gap-2 mb-2">
                              <span className={`text-[10px] px-1.5 py-0.5 rounded-full font-medium ${statusColors[status]}`}>{statusLabels[status]}</span>
                              <span className="text-[10px] text-slate-400">{statusTasks.length}件</span>
                            </div>
                            <div className="space-y-1.5">
                              {statusTasks.map(task => (
                                <div key={task.id} className="flex items-center gap-2.5 px-3 py-2 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors">
                                  <span className="flex-1 text-sm text-slate-700 truncate">{task.title}</span>
                                  {task.due_date && (
                                    <span className="text-[10px] text-slate-400 shrink-0 flex items-center gap-0.5">
                                      <Clock className="w-3 h-3" />
                                      {new Date(task.due_date).toLocaleDateString('ja-JP', { month: 'short', day: 'numeric' })}
                                    </span>
                                  )}
                                  <MoreMenu items={[
                                    { label: '削除', icon: <Trash2 className="w-3 h-3" />, onClick: () => setDeleteDialog({ type: 'task', id: task.id, name: task.title }), variant: 'danger' },
                                  ]} />
                                </div>
                              ))}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  )}
                </div>
              )}

              {/* PJレベル: 検討ツリー（V2新規 — プレースホルダー） */}
              {activeNav.type === 'project' && activeNav.tab === 'decision-tree' && (
                <div className="p-6">
                  <h2 className="text-sm font-bold text-slate-800 mb-4">{currentProject?.name} - 検討ツリー</h2>
                  <div className="flex flex-col items-center justify-center py-20 text-slate-400">
                    <GitBranch className="w-12 h-12 mb-3 text-slate-300" />
                    <p className="text-sm font-medium text-slate-500 mb-1">準備中</p>
                    <p className="text-xs text-slate-400">会議録アップロードから検討ツリーを自動生成します</p>
                  </div>
                </div>
              )}

              {/* PJレベル: 思考マップ（V2統合 — プレースホルダー） */}
              {activeNav.type === 'project' && activeNav.tab === 'thought-map' && (
                <div className="p-6">
                  <h2 className="text-sm font-bold text-slate-800 mb-4">{currentProject?.name} - 思考マップ</h2>
                  <div className="flex flex-col items-center justify-center py-20 text-slate-400">
                    <Map className="w-12 h-12 mb-3 text-slate-300" />
                    <p className="text-sm font-medium text-slate-500 mb-1">準備中</p>
                    <p className="text-xs text-slate-400">マイルストーン間の思考経路を可視化します</p>
                  </div>
                </div>
              )}

              {/* PJレベル: ジョブ（V2統合 — プレースホルダー） */}
              {activeNav.type === 'project' && activeNav.tab === 'jobs' && (
                <div className="p-6">
                  <h2 className="text-sm font-bold text-slate-800 mb-4">{currentProject?.name} - ジョブ</h2>
                  <div className="flex flex-col items-center justify-center py-20 text-slate-400">
                    <Briefcase className="w-12 h-12 mb-3 text-slate-300" />
                    <p className="text-sm font-medium text-slate-500 mb-1">準備中</p>
                    <p className="text-xs text-slate-400">定型業務・ルーティンをこのプロジェクトに紐づけて管理します</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
      {/* 削除確認ダイアログ */}
      <DeleteConfirmDialog
        isOpen={!!deleteDialog}
        onClose={() => setDeleteDialog(null)}
        onConfirm={handleDeleteConfirm}
        title={deleteDialog ? `${deleteDialog.type === 'project' ? 'プロジェクト' : 'タスク'}「${deleteDialog.name}」を削除しますか？` : ''}
        description={deleteDialog?.type === 'project'
          ? 'この操作は取り消せません。\n関連するタスク・ジョブとの紐づけが解除されます。'
          : 'この操作は取り消せません。'}
        confirmText={deleteDialog?.type === 'project' ? deleteDialog.name : undefined}
        isLoading={isDeleting}
      />
    </AppLayout>
  );
}
