-- ============================================
-- NodeMap: 全テーブルデータ削除（開発テスト用）
-- 実行: Supabase SQL Editor にペーストして Run
-- 注意: TRUNCATE CASCADE で全データが完全削除されます
-- ============================================

TRUNCATE TABLE
  business_events,
  checkpoints,
  cluster_nodes,
  consultations,
  contact_channels,
  contact_persons,
  decision_log,
  decision_tree_node_history,
  decision_tree_nodes,
  decision_trees,
  drive_documents,
  drive_file_staging,
  drive_folders,
  edge_tasks,
  email_blocklist,
  evaluation_learnings,
  goals,
  groups,
  idea_memos,
  inbox_messages,
  inbox_sync_state,
  jobs,
  knowledge_clustering_proposals,
  knowledge_domains,
  knowledge_fields,
  knowledge_master_entries,
  meeting_agenda,
  meeting_records,
  memo_conversations,
  message_reactions,
  milestone_evaluations,
  milestones,
  node_clusters,
  node_edges,
  node_master_links,
  node_source_contexts,
  open_issues,
  organization_channels,
  organizations,
  project_channels,
  project_members,
  project_recurring_rules,
  project_types,
  projects,
  secretary_conversations,
  seed_conversations,
  seeds,
  task_conversations,
  task_external_resources,
  task_members,
  task_negotiations,
  task_suggestions,
  task_templates,
  tasks,
  thinking_logs,
  thought_edges,
  thought_snapshots,
  thought_task_nodes,
  unified_messages,
  user_channel_subscriptions,
  user_nodes,
  user_service_tokens,
  user_thinking_tendencies,
  weekly_node_confirmations
CASCADE;

SELECT 'All tables truncated successfully.' AS result;
